/* =====================================================================
   Données de révision — Vie politique contemporaine
   Cours de Benjamin Lecoq-Pujade (L2, sociologie politique).
   Extraites des notes Obsidian (4 leçons) :
     1. L'État et les gouvernants
     2. Les partis politiques
     3. Les citoyens (démocratie électorale & mobilisations)
     4. Les instances de médiation sociale (société civile & opinion publique)

   Entrées CLASSÉES PAR CHAPITRE (champ « th »), dans l'ordre du cours
   (voir window.THEME_ORDER ci-dessous).

   Chaque entrée :
     t  : type  -> "auteur" (auteur/penseur) | "notion" (notion/concept) | "texte" (loi/jurisprudence/ouvrage/article) | "date" (date/événement/repère)
     th : thème -> nom du chapitre (sert au filtrage)
     r  : référence (recto de la flashcard)
     m  : signification (verso de la flashcard)

   Pour ajouter une entrée, copiez une ligne et adaptez-la, puis rouvrez index.html.
   ===================================================================== */

window.THEME_ORDER = [
  "Intro · Qu'est-ce que la vie politique ?",
  "Intro · L'État, le pouvoir & les forces politiques",
  "L'État · De l'État parlementaire à l'État exécutif",
  "L'État · Les figures du gouvernant",
  "Partis · Définition & reconnaissance juridique",
  "Partis · Typologie & organisation (4 générations)",
  "Partis · Les fonctions des partis",
  "Partis · Partis & régimes politiques",
  "Citoyens · Le sens politique de l'élection",
  "Citoyens · Les modes de scrutin",
  "Citoyens · La participation institutionnelle",
  "Citoyens · Les mobilisations spontanées",
  "Médiation · La société civile",
  "Médiation · L'opinion publique & les médias"
];

window.REPERTOIRE = [

/* ============================================================
   0. INTRO · QU'EST-CE QUE LA VIE POLITIQUE ?
   ============================================================ */
{t:"notion", th:"Intro · Qu'est-ce que la vie politique ?", r:"La vie politique (définition)", m:`Dans une société et un État donnés, l'ensemble des activités et pratiques relatives à la conquête et à l'exercice du pouvoir, ainsi qu'à la concurrence entre individus et groupes pour en influencer les orientations.`},
{t:"notion", th:"Intro · Qu'est-ce que la vie politique ?", r:"« Le » politique / « la » politique", m:`LE politique = la structure d'un groupement humain (institutions, principes, valeurs, symboles) qui fait d'une multitude un organisme collectif. LA politique = une activité sociale spécifique (perspective dynamique) — c'est elle qu'on étudie surtout.`},
{t:"notion", th:"Intro · Qu'est-ce que la vie politique ?", r:"Pourquoi la politique n'est définissable ni par sa finalité ni par son objet", m:`Finalité : la philosophie politique lui en a attribué de multiples sans s'accorder (bonheur, salut, conservation, droits individuels, justice sociale). Objet : aucun problème n'est intrinsèquement politique ; tout problème social peut le devenir s'il suscite une réponse des gouvernants.`},
{t:"notion", th:"Intro · Qu'est-ce que la vie politique ?", r:"La politique selon Weber", m:`« Le fait de chercher à participer au pouvoir ou à influer sur sa répartition. » Weber définit la politique par ses moyens plutôt que par ses fins (conférence de 1919).`},
{t:"notion", th:"Intro · Qu'est-ce que la vie politique ?", r:"L'État selon Weber", m:`« Une communauté humaine qui, à l'intérieur d'un territoire déterminé, revendique pour elle-même le monopole de la violence légitime. » L'État s'appuie sur deux moyens : le monopole de la violence et un discours de légitimation.`},
{t:"notion", th:"Intro · Qu'est-ce que la vie politique ?", r:"Le « champ » politique (Bourdieu)", m:`Espace social autonome qui recrute ses propres agents spécialisés, obéit à ses règles, produit son langage et poursuit ses fins. C'est à la fois un champ de lutte (concurrence pour le pouvoir, offre politique, clivages) et un champ de force (équilibre variable entre forces antagonistes).`},
{t:"notion", th:"Intro · Qu'est-ce que la vie politique ?", r:"La science politique", m:`Discipline autonome depuis la fin du XIXe s., dont l'objet est de décrire empiriquement les phénomènes politiques (sans jugement de valeur). 4 branches : théorie politique, relations internationales, science administrative, sociologie politique.`},
{t:"notion", th:"Intro · Qu'est-ce que la vie politique ?", r:"« Arc républicain »", m:`Notion forgée par le personnel politique lui-même pour inclure certaines formations et en exclure d'autres (jugées non acceptables) : illustre comment le champ politique structure son propre langage et ses clivages.`},
{t:"notion", th:"Intro · Qu'est-ce que la vie politique ?", r:"« Libertés-support »", m:`Libertés sur lesquelles s'appuie la spontanéité des forces sociales : association, expression, opinion, presse, réunion, syndicale, académique. Elles contribuent à définir une société démocratique.`},
{t:"texte", th:"Intro · Qu'est-ce que la vie politique ?", r:"« La vie politique en France » (René Rémond)", m:`Ouvrage en 3 tomes de l'historien René Rémond : « Les pouvoirs régulièrement institués […] n'absorbent jamais toutes les forces d'une société. »`},
{t:"texte", th:"Intro · Qu'est-ce que la vie politique ?", r:"« Traité de science politique » (Burdeau)", m:`Georges Burdeau y donne une définition résiduelle : « Des hommes qui commandent, d'autres qui obéissent, tel est […] le squelette irréductible de la vie politique. »`},
{t:"texte", th:"Intro · Qu'est-ce que la vie politique ?", r:"« La profession et la vocation des politiques » (Weber, 1919)", m:`Conférence où Weber définit la politique par ses moyens, livre la définition de l'État (monopole de la violence légitime) et celle de la politique (participer au pouvoir / influer sur sa répartition).`},
{t:"texte", th:"Intro · Qu'est-ce que la vie politique ?", r:"« Tableau politique de la France de l'Ouest » (Siegfried)", m:`André Siegfried y inaugure l'analyse des comportements électoraux (sociologie électorale), pavant la voie à la pratique des sondages.`},
{t:"date", th:"Intro · Qu'est-ce que la vie politique ?", r:"1879 — École libre des sciences politiques", m:`Création à Paris de « Sciences Po » : étape cruciale de l'émancipation de la science politique, qui vient compléter et nuancer l'approche formaliste des juristes publicistes.`},
{t:"date", th:"Intro · Qu'est-ce que la vie politique ?", r:"1903 — Ostrogorski, premier ouvrage sur les partis", m:`« La démocratie et l'organisation des partis politiques » : premier ouvrage consacré au phénomène partisan.`},

/* ============================================================
   0bis. INTRO · L'ÉTAT, LE POUVOIR & LES FORCES POLITIQUES
   ============================================================ */
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"Le décalage droit / réalité politique", m:`La vie politique d'un pays ne se réduit pas au cadre constitutionnel. Les rapports de force (politiques, économiques, sociaux, idéologiques) trouvent leur source dans la société et excèdent le raisonnement juridique. Mais le droit n'est ni impuissant ni tout-puissant.`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"Définition juridique de l'État", m:`Bodin, Carré de Malberg : une corporation politique constituée par le monopole de la puissance publique sur un territoire et une population, à laquelle le droit reconnaît la souveraineté et la personnalité morale. Esmein : « la personnification juridique d'une nation ».`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"L'État comme « institution » (Hauriou)", m:`Juste milieu entre Marx et Duguit : l'État est une institution — communauté politique organisée, permanente, reconnue par le milieu social. Le droit ne fait que tirer les conséquences de cette réalité sociale préexistante.`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"L'État, « mystification » (Duguit)", m:`Via la théorie du service public : l'État comme personne morale souveraine est une mystification. La seule réalité sociale est le rapport gouvernants/gouvernés.`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"L'État, appareil de domination de classe (Marx)", m:`Dans « Le Capital » (1867), l'État est l'appareil de domination de la classe bourgeoise sur le prolétariat ; il deviendra inutile dans la société sans classes (après la révolution prolétarienne).`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"L'État selon « Économie et société » (Weber, 1921)", m:`« Une entreprise politique à caractère institutionnel dont la direction administrative revendique avec succès le monopole de la contrainte physique légitime. »`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"Le triple processus historique de l'État", m:`Du point de vue sociopolitique, l'État résulte de : (1) la différenciation (spécialisation de l'activité politique), (2) la concentration du pouvoir de contrainte (l'État exproprie la justice privée), (3) l'institutionnalisation (pouvoir exercé au nom de la collectivité).`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"Du gouvernement à la gouvernance", m:`Gouvernement = pouvoir de direction monopolistique, centralisé, national. Gouvernance (sociologie des organisations, années 1990) = pouvoir de régulation entre acteurs publics et privés, à plusieurs niveaux. L'État passe d'une puissance de direction à une autorité de régulation.`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"L'État, catalyseur du champ politique", m:`Face officielle de la vie politique (cadre institutionnel) + autorité vers qui convergent les attentes de la société. L'État cristallise les enjeux du combat politique et dispose d'un pouvoir d'impulsion et d'attraction, sans pour autant épuiser le champ politique.`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"Les forces collectives organisées", m:`Forces institutionnalisées : l'État et les pouvoirs publics, le corps électoral, les partis politiques (« entreprises politiques »), les mouvements intermédiaires (associations, syndicats, lobbies), parfois la religion et l'armée.`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"Les forces collectives spontanées", m:`Les mouvements sociaux : protestations collectives revendiquant un changement et recourant à des moyens non institutionnels (logique « bottom-up »). Ex. Gilets jaunes, mouvements contre la réforme des retraites.`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"Les forces immatérielles (diffuses)", m:`Véhiculées par le langage (qui forge les représentations collectives). Deux principales : l'opinion publique (à étudier par ses vecteurs : presse, réseaux) et les idéologies (systèmes de croyances proposant un projet collectif : libéralisme, socialisme, nationalisme, écologie).`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"Les trois âges de la démocratie", m:`Glissements de fond depuis le XIXe s. : d'une oligarchie délibérant à huis clos, à une démocratie d'opinion (liberté de la presse), puis à une démocratie électorale (SUD), puis à une démocratie de masse.`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"La sédimentation politique", m:`L'histoire politique d'un pays est un processus de sédimentation : chaque expérience lègue un héritage, et ces héritages se superposent (ex. le « Nouveau Front populaire » de 2024, référence à 1936). Le débat est saturé de références historiques.`},
{t:"notion", th:"Intro · L'État, le pouvoir & les forces politiques", r:"La souveraineté de l'État, un absolu relatif", m:`Présentée en droit comme absolue (compétence de la compétence), la souveraineté est politiquement relativisée par l'internationalisation et l'intégration à l'UE (ex. Mercosur, principe de non-ingérence).`},
{t:"date", th:"Intro · L'État, le pouvoir & les forces politiques", r:"1867 — Marx, « Le Capital »", m:`Conception de l'État comme appareil de domination de la classe bourgeoise sur le prolétariat.`},
{t:"date", th:"Intro · L'État, le pouvoir & les forces politiques", r:"1921 — Weber, « Économie et société »", m:`Définition sociopolitique de l'État : entreprise politique au monopole de la contrainte physique légitime.`},

/* ============================================================
   1. L'ÉTAT · DE L'ÉTAT PARLEMENTAIRE À L'ÉTAT EXÉCUTIF
   ============================================================ */
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"L'État parlementaire", m:`État dont le centre d'impulsion politique réside dans le Parlement, organe (une ou deux chambres) chargé de représenter la volonté du pays, classiquement investi du pouvoir législatif et budgétaire. Cœur de la vie politique du XIXe s.`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"L'État exécutif", m:`Système (quel que soit le régime) où le centre de gravité de la vie politique s'est déplacé du Parlement vers l'exécutif. À partir du XXe s., le « règne de la discussion » cède la place au « règne de l'action ».`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"La délibération", m:`Mode décisionnel privilégié de l'État parlementaire : confronter arguments et contre-arguments pour parvenir à une décision commune ou majoritaire. D'abord une contrainte technique (le pouvoir appartient à des assemblées nombreuses).`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"La loi, expression de la volonté générale", m:`Double lecture (art. 6 DDHC) : œuvre rationnelle (la loi retranscrit les préceptes de la raison) ou expression d'une volonté souveraine juste car majoritaire. Justifie le règne de la délibération.`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"Le parlementarisme républicain", m:`Synthèse opérée par la IIIe République entre deux traditions : le parlementarisme de la monarchie de Juillet (1830-1848) et le républicanisme hérité de la Révolution. La Ve République en est encore tributaire.`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"« Parlementarisme absolu »", m:`Critique de Carré de Malberg dénonçant la sacralisation du Parlement comme traduction parfaite de la volonté générale et la subordination de l'exécutif.`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"« Parlement gouvernant »", m:`Expression de Philippe Lauvaux désignant l'hypertrophie du rôle du Parlement (même critique que le « parlementarisme absolu » de Carré de Malberg).`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"L'efficacité gouvernementale", m:`Nouveau « mot d'ordre » devenu dogme dans l'entre-deux-guerres : face à l'urgence (guerre, crises), la rationalité délibérante cède devant la rapidité de l'action exécutive.`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"« Gouverner, c'est légiférer »", m:`Idée de René Capitant (années 30) : gouverner n'est plus agir dans le cadre des lois existantes mais diriger la législation elle-même. L'exécutif impulse et maîtrise le législatif.`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"L'autonomie fonctionnelle de l'exécutif", m:`Reconnaissance à l'exécutif d'un pouvoir de décision autonome, qui n'est plus exclusivement tributaire d'une autorisation parlementaire préalable (pouvoir normatif propre).`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"Les décrets-lois", m:`Actes par lesquels le Parlement habilite le gouvernement à prendre des mesures législatives dans des domaines de sa compétence (législation déléguée). Héritage repris par les art. 37 et 38 de la Constitution de 1958.`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"La théorie des pouvoirs inhérents (USA)", m:`Affirmation, au profit du président américain, d'un pouvoir normatif autonome et concurrent du Congrès (executive orders, executive agreements non ratifiés par le Sénat mais politiquement contraignants).`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"L'autonomie organique de l'exécutif", m:`Existence institutionnelle distincte du Parlement + appui sur une administration et des services propres. Les exécutifs des années 30-40 se dotent d'un appareil administratif (poste de commande).`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"La rationalisation du parlementarisme", m:`Réglementation juridique des pratiques qui régissaient les rapports exécutif/législatif, afin d'assurer la stabilité gouvernementale. Constatée dès 1928 par Mirkin-Guetzévitch dans les constitutions d'après 1re GM.`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"La motion de défiance constructive", m:`Mécanisme allemand (Loi fondamentale de 1949) : pour renverser le chancelier (élu à la majorité absolue du Bundestag), il faut élire simultanément un successeur. Assure la stabilité de l'exécutif.`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"La théorie des circonstances exceptionnelles", m:`Jurisprudence permettant à l'exécutif/l'administration de prendre, en période de crise, des mesures illégales en temps normal (CE 1918 Heyriès ; CE 1919 Dames Dol et Laurent).`},
{t:"notion", th:"L'État · De l'État parlementaire à l'État exécutif", r:"Taylorisme & Fayolisme", m:`Doctrines industrielles inspirant la réforme gouvernementale des années 30 : le taylorisme (spécialiser les tâches entre ministères) et le fayolisme (coordination par un chef). Le gouvernement conçu comme « machine à produire de la décision ».`},
{t:"auteur", th:"L'État · De l'État parlementaire à l'État exécutif", r:"François Guizot", m:`Fondateur de la théorie de la souveraineté de la raison : le législateur retranscrit dans le droit positif les préceptes d'une raison accessible à l'entendement. Justifie la délibération comme maïeutique.`},
{t:"auteur", th:"L'État · De l'État parlementaire à l'État exécutif", r:"Nicolas de Condorcet", m:`A élaboré des systèmes de délibération mathématiques pour garantir que la décision de la majorité exprime toujours une vérité rationnelle.`},
{t:"auteur", th:"L'État · De l'État parlementaire à l'État exécutif", r:"Woodrow Wilson", m:`Politiste et président américain : « le régime de la discussion » est « le seul genre de gouvernement acceptable pour un peuple qui essaie de se gouverner lui-même ». Critique aussi le « gouvernement congressionnel ».`},
{t:"auteur", th:"L'État · De l'État parlementaire à l'État exécutif", r:"John Stuart Mill", m:`« Le rôle d'une assemblée parlementaire n'est pas de gouverner mais de contrôler le gouvernement. »`},
{t:"auteur", th:"L'État · De l'État parlementaire à l'État exécutif", r:"Walter Bagehot", m:`Pour lui la principale fonction du Parlement n'est pas de gouverner mais la fonction élective : désigner le gouvernement et contrôler son action.`},
{t:"auteur", th:"L'État · De l'État parlementaire à l'État exécutif", r:"Harvey Mansfield Jr — « Le Prince apprivoisé »", m:`Politologue américain qui théorise la notion de pouvoir exécutif : héritier direct du pouvoir absolutiste royal, le « prince » doit être « apprivoisé » (limité) par le constitutionnalisme libéral.`},
{t:"auteur", th:"L'État · De l'État parlementaire à l'État exécutif", r:"René Capitant", m:`Constitutionnaliste : dans les années 30, théorise que « gouverner, c'est désormais diriger la législation elle-même » (l'exécutif impulse la loi pour mettre en œuvre son projet).`},
{t:"auteur", th:"L'État · De l'État parlementaire à l'État exécutif", r:"Nicolas Roussellier — « La Force de gouverner » (2015)", m:`Constate que dans les années 20-30 s'opère une « disqualification de la méthode parlementaire », jugée inadaptée aux réalités politiques modernes.`},
{t:"auteur", th:"L'État · De l'État parlementaire à l'État exécutif", r:"Boris Mirkin-Guetzévitch", m:`Spécialiste de droit constitutionnel comparé : dès 1928, constate que les constitutions adoptées après la 1re GM se caractérisent par une rationalisation du parlementarisme.`},
{t:"auteur", th:"L'État · De l'État parlementaire à l'État exécutif", r:"Léon Blum — « Lettres sur la réforme gouvernementale » (1918)", m:`Préconise de faire du président du Conseil (ancêtre du PM) un véritable chef de gouvernement moderne, doté de services propres et maîtrisant le travail législatif.`},
{t:"auteur", th:"L'État · De l'État parlementaire à l'État exécutif", r:"André Tardieu — « La Réforme de l'État » (1934)", m:`Appelle à un changement de régime où un « Premier ministre » s'appuierait sur une majorité stable avec droit de dissolution. Inspire de Gaulle et Debré pour la Constitution de 1958.`},
{t:"auteur", th:"L'État · De l'État parlementaire à l'État exécutif", r:"Max Weber — la bureaucratie", m:`Théorise la bureaucratie comme forme rationnelle d'organisation du pouvoir : respect de la règle de droit, spécialisation des tâches, fonctionnaires recrutés par concours.`},
{t:"texte", th:"L'État · De l'État parlementaire à l'État exécutif", r:"Article 6 de la DDHC (1789)", m:`« La loi est l'expression de la volonté générale. » Fondement idéologique du règne de la délibération et de la suprématie de la loi.`},
{t:"texte", th:"L'État · De l'État parlementaire à l'État exécutif", r:"CE, 1918, Heyriès", m:`En cas de circonstances exceptionnelles, l'exécutif peut prendre des mesures qu'il ne pourrait pas adopter en période normale.`},
{t:"texte", th:"L'État · De l'État parlementaire à l'État exécutif", r:"CE, 1919, Dames Dol et Laurent", m:`Consacre la théorie des circonstances exceptionnelles : l'administration peut restreindre les libertés publiques (zone de guerre) au nom de l'ordre public et de la défense nationale.`},
{t:"texte", th:"L'État · De l'État parlementaire à l'État exécutif", r:"Articles 37 et 38 de la Constitution de 1958", m:`Héritiers de la pratique des décrets-lois : pouvoir réglementaire autonome (art. 37) et ordonnances de l'art. 38 (le gouvernement légifère sur habilitation).`},
{t:"date", th:"L'État · De l'État parlementaire à l'État exécutif", r:"La crise du 16 mai 1877", m:`Crise opposant le président Mac-Mahon à la Chambre républicaine ; sa résolution consacre la souveraineté du Parlement et la supériorité du travail parlementaire (avènement de l'État parlementaire « par excellence »).`},
{t:"date", th:"L'État · De l'État parlementaire à l'État exécutif", r:"1934 — Matignon & secrétariat général de la présidence du Conseil", m:`Pour la première fois la présidence du Conseil est dotée d'un local (Matignon) et de services propres : poste de commande opérationnel du pouvoir gouvernemental (ancêtre du SGG).`},
{t:"date", th:"L'État · De l'État parlementaire à l'État exécutif", r:"1939 — Executive Office of the President (USA)", m:`Création de la « White House Office » : centrale administrative (≈1800 agents) qui conseille le président, gère sa communication, sonde l'opinion. Symbole de l'autonomie organique de l'exécutif.`},

/* ============================================================
   2. L'ÉTAT · LES FIGURES DU GOUVERNANT
   ============================================================ */
{t:"notion", th:"L'État · Les figures du gouvernant", r:"La différenciation de l'activité politique", m:`Processus par lequel la politique se distingue des autres activités sociales ; elle finit par être confiée à un personnel spécialisé. Condition d'apparition des démocraties contemporaines.`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"La division du travail social (Durkheim)", m:`Dans les sociétés modernes, la cohésion repose sur la différenciation et la complémentarité des fonctions (solidarité « organique »). La spécialisation politique en découle.`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"La professionnalisation de la politique", m:`Selon Weber, l'homme/la femme politique vit « pour » la politique (vocation) et « de » la politique (rétribution) : il/elle y consacre l'essentiel de son temps.`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"La « classe politique »", m:`Idée que l'activité politique est monopolisée par un groupe social homogène et hermétique, réservé à ceux qui disposent des capitaux social, économique et culturel (diplômes, relations).`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"Le notable", m:`Première figure de l'État parlementaire : personne de rang social élevé (aristocratie ou haute bourgeoisie d'affaires), élue sur son prestige social, pratiquant la politique en amateur grâce à son aisance financière.`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"Le suffrage censitaire", m:`Droit de vote réservé aux contribuables payant un cens (impôt). Assure l'auto-sélection d'une classe de possédants (sous la Restauration : ≈0,27 % de la population vote).`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"La « Gentry » (R-U)", m:`Classe sociale de la noblesse non-titrée et de la haute bourgeoisie industrielle ; équivalent britannique du système notabiliaire français.`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"Le tribun", m:`Deuxième figure (âge d'or de la IIIe Rép.) : orateur qui, par son éloquence à la tribune, emporte la conviction de l'assemblée. Émerge avec la politisation populaire et la campagne électorale.`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"La « République des avocats »", m:`Sous la IIIe République, les professions libérales/intellectuelles forment les 2/3 des parlementaires ; les avocats représentent à eux seuls ≈1/3 de la Chambre des députés.`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"L'homme / la femme d'État", m:`Troisième figure : profil parlementaire hissé par l'éloquence MAIS doté d'une expérience des rouages de l'État ; cultive une culture de l'intérêt général par-delà les divisions partisanes. Marque le basculement vers l'État exécutif.`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"Le « spoils system » (USA)", m:`« Au vainqueur les dépouilles » (théorisé sous A. Jackson) : le président remplace une partie des fonctionnaires fédéraux par ses partisans. S'oppose au modèle français de stabilité/neutralité (concours).`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"Le technicien / la technocrate", m:`Quatrième et dernière figure : promu·e aux responsabilités exécutives à raison de sa compétence technique. Culte de la maîtrise des dossiers et de l'efficacité, contre le « culte de la parole ».`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"L'inversion du cursus honorum", m:`Sous la Ve République, le parcours Sciences Po / ENA devient la voie « royale » de recrutement des élites, supplantant l'ascension classique de l'élu local.`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"Le pantouflage", m:`Fait, pour un haut fonctionnaire, de passer quelques années dans le secteur privé avant d'entrer dans les cabinets ministériels.`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"Le parachutage", m:`Fait d'investir un candidat aux élections dans une circonscription où il n'a aucune attache locale particulière.`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"La « noblesse d'État » (Bourdieu)", m:`Homogénéisation du personnel dirigeant (énarques) et constitution d'un « esprit de corps » : solidarité d'intérêts s'appuyant sur des réseaux tentaculaires.`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"Le ministre, « agent double »", m:`Le ministre est à la fois chef politique (élu, légitimité politique) et chef d'une machine administrative (hauts fonctionnaires, légitimité professionnelle). Duo de légitimités de l'État providence.`},
{t:"notion", th:"L'État · Les figures du gouvernant", r:"Le « cens caché » — voir aussi élection", m:`(D. Gaxie) Barrières sociales et culturelles qui, dans les faits, limitent l'exercice du suffrage universel proclamé en droit — ce qui maintient longtemps les élites notabiliaires au pouvoir.`},
{t:"auteur", th:"L'État · Les figures du gouvernant", r:"Émile Durkheim — « De la division du travail social » (1893)", m:`Théorise que la cohésion des sociétés modernes repose sur la différenciation des fonctions (solidarité organique). Cadre de la spécialisation de l'activité politique.`},
{t:"auteur", th:"L'État · Les figures du gouvernant", r:"Sieyès", m:`Dès 1789 : la représentation politique n'est qu'une déclinaison de la division du travail. Le peuple, occupé par ses tâches, n'a pas le loisir de gouverner ; la politique doit revenir à un personnel spécialisé.`},
{t:"auteur", th:"L'État · Les figures du gouvernant", r:"Max Weber — vivre « pour » et « de » la politique", m:`Théorise au début du XXe s. la professionnalisation : le professionnel de la politique en fait sa vocation et en attend une rétribution.`},
{t:"auteur", th:"L'État · Les figures du gouvernant", r:"Pierre Bourdieu — la « noblesse d'État »", m:`Analyse la création d'une nouvelle élite dirigeante (énarques) homogène socialement, soudée par un « esprit de corps ».`},
{t:"auteur", th:"L'État · Les figures du gouvernant", r:"Alphonse de Lamartine / Alexis de Tocqueville (le cursus du notable)", m:`Exemples de notables de province : ils commencent conseiller général, exploitent leurs attaches locales pour se faire élire député, puis ministre des Affaires étrangères.`},
{t:"auteur", th:"L'État · Les figures du gouvernant", r:"Pierre Mendès France — « Gouverner, c'est choisir »", m:`Grande figure de la IVe Rép. ; sa formule marque le changement de culture politique, de la délibération à l'action (figure de l'homme d'État).`},
{t:"texte", th:"L'État · Les figures du gouvernant", r:"Article 23 de la Constitution de 1958", m:`Incompatibilité entre les fonctions gouvernementales et le mandat parlementaire. Facteur (juridique) de « dépolitisation » du personnel gouvernemental sous la Ve République.`},
{t:"date", th:"L'État · Les figures du gouvernant", r:"5 mars 1848 — suffrage universel masculin", m:`9 millions d'électeurs accèdent au suffrage. Malgré cela, les élites notabiliaires se maintiennent (élections de 1849 : « Parti de l'ordre » ; 1871 : « République des ducs »).`},
{t:"date", th:"L'État · Les figures du gouvernant", r:"21 avril 1944 — droit de vote des femmes", m:`L'ordonnance accorde le droit de vote aux femmes (refusé depuis la Révolution). En 1945, 33 femmes entrent à l'Assemblée ; 1947 : G. Poinso-Chapuis, 1re femme ministre de plein exercice ; 1991-92 : É. Cresson, 1re Première ministre.`},
{t:"date", th:"L'État · Les figures du gouvernant", r:"1936 — trois femmes au gouvernement Blum", m:`Premières sous-secrétaires d'État (avant même le droit de vote des femmes) : Cécile Brunschvicg (Éducation), Suzanne Lacore (Santé/Enfance), Irène Joliot-Curie (Recherche).`},
{t:"date", th:"L'État · Les figures du gouvernant", r:"Novembre 1958 — élections législatives", m:`« Hécatombe » des anciens parlementaires : la SFIO passe de 94 à 40 sièges, le parti gaulliste obtient 206 sièges. Plus de la moitié du gouvernement Debré est issue de la haute fonction publique.`},
{t:"date", th:"L'État · Les figures du gouvernant", r:"Georges Pompidou (2e PM de la Ve)", m:`Premier chef de gouvernement français, en période normale, à n'avoir jamais été élu par le Parlement. Illustre la figure du technicien et le nouveau rôle (contrôle, non détermination) des parlementaires.`},
{t:"date", th:"L'État · Les figures du gouvernant", r:"La Libération — création des IEP et de l'ENA", m:`Faire de la politique un domaine de formation à part entière et former les grands commis de l'État. La voie Sciences Po/ENA devient royale (Giscard, Chirac, Hollande, Macron sont énarques).`},

/* ============================================================
   3. PARTIS · DÉFINITION & RECONNAISSANCE JURIDIQUE
   ============================================================ */
{t:"notion", th:"Partis · Définition & reconnaissance juridique", r:"Le parti politique (définition doctrinale)", m:`Organisation relativement stable de citoyens partageant une affinité idéologique commune, qui, par la recherche du soutien populaire, vise à conquérir et exercer le pouvoir.`},
{t:"notion", th:"Partis · Définition & reconnaissance juridique", r:"Définition sociologique de Weber (les « sociations »)", m:`Les partis sont des « sociations » (relations fondées sur un engagement libre) visant à procurer le pouvoir à leur chef et des avantages/objectifs à leurs militants. Identifiables par 3 traits : organisation, but (le pouvoir), moyens (lutte électorale + partage des postes).`},
{t:"notion", th:"Partis · Définition & reconnaissance juridique", r:"Un phénomène para-constitutionnel", m:`Les partis sont apparus spontanément à la faveur du suffrage universel, en marge des textes constitutionnels. D'où la difficulté de la doctrine juridique à les théoriser (la science politique y parvient mieux).`},
{t:"notion", th:"Partis · Définition & reconnaissance juridique", r:"La faction", m:`Groupe d'individus menant une activité fractionnelle et subversive pour faire prévaloir ses intérêts particuliers contre l'intérêt général. Distincte du parti (n'admet pas le pluralisme).`},
{t:"notion", th:"Partis · Définition & reconnaissance juridique", r:"La dissolution administrative (des groupements)", m:`Pouvoir du gouvernement de dissoudre certaines associations/groupements (recours aux armes, milice privée, atteinte par la force à la forme républicaine). Né de la loi du 10 juillet 1936, aujourd'hui art. L. 212-1 du Code de la sécurité intérieure.`},
{t:"notion", th:"Partis · Définition & reconnaissance juridique", r:"Les ligues", m:`Groupements d'extrême droite (Action française, Croix-de-Feu) nés autour de l'affaire Dreyfus, composés d'anciens combattants ; nourrissent un sentiment antiparlementaire et antirépublicain dans les années 30.`},
{t:"auteur", th:"Partis · Définition & reconnaissance juridique", r:"Ostrogorski — « La Démocratie et l'organisation des partis politiques » (1903)", m:`Fondateur de la science politique : souligne que les partis assurent une liaison continue entre société et dirigeants. Le Parlement n'est plus « que la grande scène où se dénoue l'action préparée ailleurs ».`},
{t:"auteur", th:"Partis · Définition & reconnaissance juridique", r:"Maurice Duverger — « Les Partis politiques » (1951)", m:`L'étude des partis est un « fil d'Ariane » dans le labyrinthe du pouvoir : « qui connaît le droit constitutionnel classique et ignore le rôle des partis n'a qu'une vue fausse des régimes politiques ».`},
{t:"auteur", th:"Partis · Définition & reconnaissance juridique", r:"Benjamin Constant (définition du parti)", m:`Définit le parti comme « une réunion d'hommes qui professent la même doctrine politique ». Définition jugée trop large (englobe les anciennes factions).`},
{t:"texte", th:"Partis · Définition & reconnaissance juridique", r:"Article 4 de la Constitution de 1958", m:`« Les partis et groupements politiques concourent à l'expression du suffrage. Ils se forment et exercent leur activité librement. Ils doivent respecter [...] la souveraineté nationale et la démocratie. » Reconnaissance tardive et partielle.`},
{t:"texte", th:"Partis · Définition & reconnaissance juridique", r:"Révision constitutionnelle de 1999 (parité)", m:`Complète l'art. 4 : associe les partis à l'objectif de mise en œuvre de la parité H/F dans l'accès aux mandats électoraux.`},
{t:"texte", th:"Partis · Définition & reconnaissance juridique", r:"Loi constitutionnelle du 23 juillet 2008", m:`Ajoute à l'art. 4 la garantie du pluralisme et de la participation équitable des partis à la vie démocratique. Base du financement public et de la régulation du temps de parole (ARCOM).`},
{t:"texte", th:"Partis · Définition & reconnaissance juridique", r:"CC, 11 janvier 1990, Limitation des dépenses électorales", m:`La libre constitution des partis et leur financement au moins partiel par l'État sont une garantie de l'expression pluraliste des courants d'opinions.`},
{t:"texte", th:"Partis · Définition & reconnaissance juridique", r:"CEDH, 7 décembre 2006, Linkov c. République tchèque", m:`Sur le fondement des art. 10 (liberté d'expression) et 11 (réunion/association) CEDH, reconnaît le rôle primordial des partis dans le bon fonctionnement d'une démocratie.`},
{t:"texte", th:"Partis · Définition & reconnaissance juridique", r:"CE, ass., 30 octobre 1996, Élections municipales de Fos-sur-Mer", m:`Définit le parti comme une personne morale de droit privé poursuivant un but politique, éligible à l'aide publique et soumise à la législation sur la transparence financière.`},
{t:"texte", th:"Partis · Définition & reconnaissance juridique", r:"Loi du 11 mars 1988 (transparence financière)", m:`Première reconnaissance positive des partis : règlementation minimaliste fixant les modalités et montants du financement public.`},
{t:"texte", th:"Partis · Définition & reconnaissance juridique", r:"Loi du 1er juillet 1901 (liberté d'association)", m:`Libéralisation tardive qui permet l'émergence des premiers partis français (années 20), alors qu'ils sont apparus dès le milieu du XIXe s. au R-U et aux USA.`},
{t:"texte", th:"Partis · Définition & reconnaissance juridique", r:"Loi du 10 juillet 1936 (groupes de combat et milices privées)", m:`Adoptée dans un contexte de « défense républicaine » face aux ligues ; fonde le pouvoir de dissolution administrative des groupements. Dispositions conservées à l'art. L. 212-1 CSI.`},
{t:"date", th:"Partis · Définition & reconnaissance juridique", r:"6 février 1934", m:`Manifestation des ligues d'extrême droite à Paris, en réaction à l'investiture du gouvernement Daladier ; les manifestants cherchent à marcher sur le Palais-Bourbon et à renverser la République.`},
{t:"date", th:"Partis · Définition & reconnaissance juridique", r:"Décret du 4 octobre 2023 — dissolution de Quirittas", m:`Exemple contemporain de dissolution administrative (initiative de G. Darmanin) : micro-parti d'extrême droite intégriste visant à substituer à la République une « cité catholique » gouvernée par un monarque.`},

/* ============================================================
   4. PARTIS · TYPOLOGIE & ORGANISATION (4 GÉNÉRATIONS)
   ============================================================ */
{t:"notion", th:"Partis · Typologie & organisation (4 générations)", r:"La « trinité » du parti (Pierre Avril)", m:`Le parti articule 3 réalités (essai de 1986) : le parti comme organisation, les électeurs, et les élus (du conseiller municipal au président). Leur articulation fonde la typologie des partis.`},
{t:"notion", th:"Partis · Typologie & organisation (4 générations)", r:"Le parti de cadres (1re génération)", m:`Né au XIXe s. (suffrage censitaire) : dynamique oligarchique, peu d'adhérents, hiérarchie descendante, financement capitaliste. Centre décisionnel = les dirigeants (notables, bourgeois). Parti de « représentation individuelle ».`},
{t:"notion", th:"Partis · Typologie & organisation (4 générations)", r:"Le groupe parlementaire", m:`Regroupement d'élus d'une même chambre par affinité politique, pour peser sur les travaux et discipliner les débats. En France, reconnu officiellement par la Chambre des députés en 1910.`},
{t:"notion", th:"Partis · Typologie & organisation (4 générations)", r:"Le parti de masses (2e génération)", m:`Né au début du XXe s. (suffrage universel, cause ouvrière) : partis de gauche, accent sur les militants, financement par cotisations, fonctionnement démocratique. Rôle d'éducation politique. Parti d'« intégration sociale ».`},
{t:"notion", th:"Partis · Typologie & organisation (4 générations)", r:"Le parti indirect", m:`(Duverger) Parti dont l'unité de base n'est pas le militant individuel mais des organisations affiliées. Exemple type : le Labour britannique, fondé par les trade unions.`},
{t:"notion", th:"Partis · Typologie & organisation (4 générations)", r:"Le parti de « peuple » (3e génération)", m:`Déclinaison des partis de masses qui prétend incarner le peuple dans sa totalité. Deux types après la 1re GM : les partis communistes (après 1917) et les partis fascistes (années 20).`},
{t:"notion", th:"Partis · Typologie & organisation (4 générations)", r:"L'avant-garde militante (Lénine)", m:`Le prolétariat étant jugé incapable de se coaliser spontanément, un parti communiste révolutionnaire doit être le moteur de la révolution et en incarner l'« avant-garde ».`},
{t:"notion", th:"Partis · Typologie & organisation (4 générations)", r:"Le parti d'encadrement social", m:`Parti « peuple » à l'organisation très structurée (cellules d'usines, embrigadement de la jeunesse, propagande, milice) qui encadre la vie sociale au-delà de la conquête électorale.`},
{t:"notion", th:"Partis · Typologie & organisation (4 générations)", r:"Le parti de rassemblement / « catch-all party » (4e génération)", m:`À partir des années 50 : « parti attrape-tout » qui délaisse une clientèle idéologique unique pour porter des valeurs universelles et séduire le plus large électorat possible (campagnes = opérations de séduction).`},
{t:"auteur", th:"Partis · Typologie & organisation (4 générations)", r:"Maurice Duverger — partis de cadres / partis de masses", m:`Établit la distinction fondatrice entre parti de cadres (oligarchique, dirigeants) et parti de masses (militants, intégration sociale). Le rôle du parti : canaliser la masse des voix par une organisation professionnelle.`},
{t:"auteur", th:"Partis · Typologie & organisation (4 générations)", r:"Norbert Elias", m:`L'apparition des partis fait passer la vie politique d'une « concurrence libre et individuelle » à une concurrence monopolistique et collective (organisée par les partis).`},
{t:"auteur", th:"Partis · Typologie & organisation (4 générations)", r:"Jules Guesde", m:`Marxiste, fondateur du courant socialiste révolutionnaire (PSDF). S'oppose à la ligne réformiste de Jaurès avant la fusion de 1905 (SFIO).`},
{t:"auteur", th:"Partis · Typologie & organisation (4 générations)", r:"Jean Jaurès", m:`Figure du socialisme réformiste (PSF). Fusionne avec le courant de Guesde pour former la SFIO (1905). Promeut aussi la ritualisation pacifique de la manifestation ouvrière.`},
{t:"texte", th:"Partis · Typologie & organisation (4 générations)", r:"Reform Act de 1832 (R-U)", m:`Assouplit le suffrage censitaire (sans suffrage universel). Faute de listes électorales, ce sont les partis qui démarchent les électeurs via les « registration societies ».`},
{t:"texte", th:"Partis · Typologie & organisation (4 générations)", r:"Representation of the People Act de 1867 (R-U)", m:`Nouvel élargissement du droit de vote ; pousse les partis à s'organiser hors du Parlement pour capter l'électorat (comités électoraux).`},
{t:"date", th:"Partis · Typologie & organisation (4 générations)", r:"Whigs & Tories (R-U, XVIIe s.)", m:`Premiers groupes parlementaires : Whigs (bourgeoisie, hostiles à l'absolutisme royal) contre Tories (origine aristocratique, favorables à l'autorité royale).`},
{t:"date", th:"Partis · Typologie & organisation (4 générations)", r:"Le « Parti de l'ordre » (1849)", m:`Coalition de la droite conservatrice (royalistes + républicains modérés) sous la IIe Rép. : un comité électoral central coordonne les comités départementaux et rafle les élections, prenant de court la gauche.`},
{t:"date", th:"Partis · Typologie & organisation (4 générations)", r:"Le SPD allemand (1875) — la social-démocratie", m:`Né de la fusion de deux courants ouvriers (réformiste + révolutionnaire). 1re force politique allemande en 1902, modèle des partis socialistes en Europe ; main mise sur les syndicats pour tempérer la radicalité.`},
{t:"date", th:"Partis · Typologie & organisation (4 générations)", r:"Le Labour Party (1900) — le travaillisme", m:`Créé à l'initiative des trade unions pour faire entrer des élus ouvriers au Parlement (« parti indirect »). Processus inverse de la social-démocratie, résultat réformiste similaire.`},
{t:"date", th:"Partis · Typologie & organisation (4 générations)", r:"La SFIO (1905) — le socialisme français", m:`Section française de l'internationale ouvrière : fusion du PSDF (Guesde) et du PSF (Jaurès) sous l'impulsion de la IIe Internationale. Ancêtre du Parti socialiste.`},
{t:"date", th:"Partis · Typologie & organisation (4 générations)", r:"La Charte d'Amiens (1906)", m:`Au Congrès de la CGT, le syndicalisme proclame son indépendance vis-à-vis du parti socialiste (crainte de l'« expérience allemande »). La cause ouvrière se divise entre parti et syndicat.`},
{t:"date", th:"Partis · Typologie & organisation (4 générations)", r:"Le Congrès de Tours (1920)", m:`Scission de la SFIO : la majorité fait sécession pour former la SFIC (futur Parti communiste français), placée sous l'autorité du parti soviétique (IIIe Internationale, créée en 1919).`},

/* ============================================================
   5. PARTIS · LES FONCTIONS DES PARTIS
   ============================================================ */
{t:"notion", th:"Partis · Les fonctions des partis", r:"Les 3 fonctions des partis", m:`Dans le modèle démocratique libéral : (1) conquérir et exercer le pouvoir par les urnes ; (2) assurer la médiation entre gouvernants et sphère publique ; (3) socialiser et former le personnel politique.`},
{t:"notion", th:"Partis · Les fonctions des partis", r:"La fonction de conquête du pouvoir", m:`Les partis sont des « machines à produire des élus » (art. 4 Ct). Ils sélectionnent les candidats (investiture, primaires, cooptation) et organisent la campagne.`},
{t:"notion", th:"Partis · Les fonctions des partis", r:"Les primaires (ouvertes / fermées)", m:`Mode américain de sélection des candidats : primaires fermées (réservées aux adhérents) ou ouvertes (tous les électeurs). Adoptées par le PS en France (2006 fermée → Royal ; 2011 ouverte → Hollande).`},
{t:"notion", th:"Partis · Les fonctions des partis", r:"L'investiture par le parti (France)", m:`Mode traditionnel de sélection des candidats par une commission d'investiture (ex. législatives 2024 organisées en temps record). La gauche tend à un mode démocratique, la droite/le centre à la cooptation.`},
{t:"notion", th:"Partis · Les fonctions des partis", r:"Le financement public des campagnes (France)", m:`Remboursement partiel des frais de campagne. Sous 5 % des voix : remboursement minimal (≈4,75 %). Au-delà de 5 % : remboursement d'environ 47,5 % des frais engagés.`},
{t:"notion", th:"Partis · Les fonctions des partis", r:"La fonction de médiation État / opinion", m:`Les partis assurent une liaison à double sens entre l'État et la société : sens ascendant (relais des opinions vers l'État) et sens descendant (structuration de l'opinion publique).`},
{t:"notion", th:"Partis · Les fonctions des partis", r:"Les partis gestionnaires", m:`Partis ayant vocation à exercer le pouvoir (majorité ou pivot de coalition). Pour se maintenir, ils adoptent une ligne souple et englobante (catch-all) afin de « brasser large ».`},
{t:"notion", th:"Partis · Les fonctions des partis", r:"Les partis protestataires", m:`Partis se faisant le véhicule du mécontentement, porte-parole des catégories exclues/oubliées. Ex. : les candidatures de témoignage, qui font de la campagne une tribune sans espoir de gagner.`},
{t:"notion", th:"Partis · Les fonctions des partis", r:"La structuration de l'opinion (sens descendant)", m:`Quand un parti impose un thème dans le débat, il oblige tous les autres à se positionner : il en fait un thème clivant et structurant (ex. l'immigration depuis les années 80 ; la laïcité depuis 1989).`},
{t:"auteur", th:"Partis · Les fonctions des partis", r:"Pierre Rosanvallon (médiation des partis)", m:`Historien et théoricien : les partis « organisent le monde politique à partir de la vie sociale » ; ils assurent un rôle de liaison entre l'État et la société.`},
{t:"date", th:"Partis · Les fonctions des partis", r:"1989 — l'affaire du foulard de Creil", m:`Point de départ qui fait de la laïcité un thème clivant de l'opinion publique : illustration de la capacité des partis (et de l'actualité) à structurer le débat.`},

/* ============================================================
   6. PARTIS · PARTIS & RÉGIMES POLITIQUES
   ============================================================ */
{t:"notion", th:"Partis · Partis & régimes politiques", r:"L'hostilité originelle française aux partis", m:`Conception individuelle du mandat parlementaire : les partis sont longtemps vus comme des factions divisant la nation souveraine et faisant écran à la relation représentant/représenté.`},
{t:"notion", th:"Partis · Partis & régimes politiques", r:"La mobilisation pré-partisane (Révolution)", m:`Les clubs révolutionnaires (ex. club des Jacobins) ne sont ni des groupes parlementaires ni des machines électorales (suffrage censitaire). Ils apparaissent comme des factions n'admettant pas la pluralité.`},
{t:"notion", th:"Partis · Partis & régimes politiques", r:"Le club des Jacobins", m:`Issu du club breton → « Société des amis de la Constitution », installé au couvent jacobin. Instance collective para-parlementaire déterminante durant la période révolutionnaire.`},
{t:"notion", th:"Partis · Partis & régimes politiques", r:"La reconnaissance « en demi-teinte »", m:`Avec le suffrage universel, les partis deviennent indispensables ; longtemps vus comme un « mal nécessaire », ils sont reconnus tardivement et partiellement (art. 4, 1958), uniquement dans leur rôle électoral.`},
{t:"notion", th:"Partis · Partis & régimes politiques", r:"Le bipartisme / dualisme", m:`Système où deux partis dominants alternent au pouvoir, assurés d'obtenir une majorité (pays anglo-saxons).`},
{t:"notion", th:"Partis · Partis & régimes politiques", r:"Le multipartisme", m:`Système où plus de deux partis significatifs coexistent sans qu'aucun n'obtienne seul une majorité (Europe continentale). Tempéré par la capacité à former des coalitions.`},
{t:"notion", th:"Partis · Partis & régimes politiques", r:"La classification classique des régimes", m:`Élaborée fin XIXe-début XXe sur un critère unique, le degré de séparation des pouvoirs : régime parlementaire (séparation souple, organes interdépendants) vs régime présidentiel (séparation stricte).`},
{t:"notion", th:"Partis · Partis & régimes politiques", r:"L'effet de distorsion du bipartisme", m:`Le bipartisme déforme la séparation officielle des pouvoirs : convergence (mêmes pouvoirs gouvernés par le même parti) ou, au contraire, rigidification (organes dominés par des partis différents).`},
{t:"notion", th:"Partis · Partis & régimes politiques", r:"Le modèle de Westminster (R-U) — fusion des pouvoirs", m:`Le bipartisme fait du PM le leader du parti majoritaire et du Cabinet la « commission exécutive » de la majorité. Discipline assurée par les whips ; déclin de la responsabilité politique (le parti remplace le PM sans élections).`},
{t:"notion", th:"Partis · Partis & régimes politiques", r:"Le « parlementarisme de couloir » (USA)", m:`Quand le président dispose d'une majorité au Congrès, il fait porter ses projets par ses alliés parlementaires (convergence opportune, non structurelle). Les midterms peuvent imposer une « cohabitation ».`},
{t:"notion", th:"Partis · Partis & régimes politiques", r:"Systèmes majoritaires vs non-majoritaires (Duverger)", m:`Nouvelle ligne de partage : systèmes majoritaires (bipartisme, gouvernement protégé par sa majorité, ex. R-U) vs systèmes non-majoritaires (multipartisme, survie négociée avec des coalitions).`},
{t:"notion", th:"Partis · Partis & régimes politiques", r:"Le fait majoritaire (Ve République)", m:`Regroupement des partis en deux blocs (droite/gauche) procurant au gouvernement une majorité stable et disciplinée derrière le Président. Né de la dissolution de 1962.`},
{t:"notion", th:"Partis · Partis & régimes politiques", r:"Les 4 leviers de binarisation (Ve)", m:`(1) Le référendum (1962, SUD présidentiel) ; (2) le droit de dissolution (1961-62) ; (3) le scrutin uninominal majoritaire à deux tours ; (4) la présidentialisation des partis (machines au service d'un candidat).`},
{t:"notion", th:"Partis · Partis & régimes politiques", r:"Le Parti radical", m:`Parti « pivot » de toutes les coalitions jusqu'en 1940 : républicain, démocrate, non socialiste mais marqué par la justice sociale et un profond anticléricalisme. Cristallise les clivages de la IIIe Rép.`},
{t:"auteur", th:"Partis · Partis & régimes politiques", r:"Walter Bagehot (classification des régimes, 1867)", m:`Auteur d'un traité sur la Constitution anglaise : distingue le « gouvernement de cabinet » (régime parlementaire, exécutif responsable) du « gouvernement présidentiel » (PR élu et irresponsable devant les chambres).`},
{t:"auteur", th:"Partis · Partis & régimes politiques", r:"Adhémar Esmein", m:`Fin XIXe : adapte la classification de Bagehot à la IIIe Rép. sur un double critère — indépendance des organes + spécialisation des fonctions (régime parlementaire/présidentiel).`},
{t:"auteur", th:"Partis · Partis & régimes politiques", r:"Tocqueville — « un mal inhérent au gouvernement libre »", m:`« Les partis sont un mal inhérent au gouvernement libre » (1835-1840) : intuition précoce que les partis, bien que dangereux, sont indissociables de la liberté politique.`},
{t:"auteur", th:"Partis · Partis & régimes politiques", r:"Hans Kelsen — « La Démocratie, sa nature, sa valeur » (1932)", m:`Rare juriste à incorporer le phénomène partisan à sa théorie de la démocratie : « la démocratie est nécessairement et inévitablement un État de partis ».`},
{t:"texte", th:"Partis · Partis & régimes politiques", r:"Décret Le Chapelier du 29 septembre 1791 (sociétés populaires)", m:`L'Assemblée constituante refuse toute existence politique aux sociétés populaires : on nie le phénomène partisan (raison théorique rousseauiste + raison politique de préservation du monopole de la volonté générale).`},
{t:"texte", th:"Partis · Partis & régimes politiques", r:"Article 49 de la Constitution italienne (1947)", m:`Les partis concourent « à la détermination de la politique nationale » : ils sont incorporés à l'État (reconnaissance très poussée, par contraste avec la France).`},
{t:"texte", th:"Partis · Partis & régimes politiques", r:"Article 21 de la Loi fondamentale allemande (1949)", m:`« Les partis concourent à la formation de la volonté politique du peuple » : ni incorporés à l'État, ni ignorés, mais reconnus comme instance de médiation nécessaire entre État et peuple.`},
{t:"date", th:"Partis · Partis & régimes politiques", r:"La crise du 16 mai 1877 (instabilité)", m:`Avec la dissension Grévy/Gambetta, consacre la souveraineté du Parlement : le chef de la majorité n'étant pas assuré du pouvoir, les parlementaires se lancent dans une « course aux portefeuilles » (instabilité ministérielle chronique).`},
{t:"date", th:"Partis · Partis & régimes politiques", r:"Le référendum de 1962 (SUD)", m:`L'élection du Président au suffrage universel direct court-circuite la médiation des partis et cristallise le débat pour/contre la vision gaullienne : amorce du fait majoritaire.`},
{t:"date", th:"Partis · Partis & régimes politiques", r:"2017 — l'élection de Macron brise le dualisme", m:`En gouvernant « au centre », Emmanuel Macron provoque l'éclatement des deux grands partis traditionnels (PS et LR/UMP) qui structuraient la vie politique depuis les années 80.`},

/* ============================================================
   7. CITOYENS · LE SENS POLITIQUE DE L'ÉLECTION
   ============================================================ */
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"Le peuple", m:`Entité collective à laquelle, en démocratie représentative, les actes des représentants sont juridiquement imputés. Il n'existe qu'en vertu de la représentation et ne se manifeste jamais spontanément et collectivement.`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"Le corps électoral", m:`Ensemble des citoyens disposant du droit de vote (≈ 48,8 millions en France). Ce n'est jamais « tout le peuple » qui se déplace aux urnes (il faut retrancher non-inscrits, mal-inscrits, abstentionnistes).`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"La citoyenneté", m:`Capacité d'un individu, membre d'une communauté politique souveraine, à prendre part aux affaires publiques. Le sens se dilate aujourd'hui (citoyenneté administrative, environnementale) ; « citoyen » devient un adjectif renvoyant à des valeurs.`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"La citoyenneté européenne", m:`Depuis le traité de Maastricht (1992), elle se superpose à la citoyenneté des États membres et se traduit par des droits (notamment économiques).`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"L'élection comme mécanisme aristocratique (Manin)", m:`À l'origine (fin XVIIIe), l'élection est conçue comme une sélection des « meilleurs » : un acte d'investiture d'une oligarchie, et non un instrument démocratique. Le lien élection/démocratie est postérieur.`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"Le sens juridique de l'élection", m:`Procédure par laquelle un corps électoral investit d'une fonction une ou plusieurs personnes qu'il choisit par son vote. Avant tout un mécanisme de sélection (définition stable depuis le XVIIIe s.).`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"Le sens sociologique de l'élection", m:`Rituel par lequel la société apporte à intervalles réguliers un surcroît de légitimité aux gouvernants ; il réactive le sentiment d'appartenance à une même communauté politique (faire corps comme nation).`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"Le vote à deux degrés (1791)", m:`Des citoyens actifs (payant un cens) élisent des électeurs du second degré, qui élisent les députés. Complété par un cens d'éligibilité : l'élection reproduit une autorité sociale au profit d'une élite notabiliaire.`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"Le « cens caché » (Daniel Gaxie)", m:`Paradoxe d'un suffrage universel proclamé en droit mais entravé en fait par des barrières sociales et culturelles. Permet le maintien des élites notabiliaires après 1848.`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"La candidature officielle (Second Empire)", m:`Contrat tacite : le gouvernement soutient activement un candidat en échange de sa docilité une fois élu. Atteinte à la liberté de vote.`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"La « Poll Tax » (USA)", m:`Taxe pour voter instaurée dans les États du Sud ségrégationnistes pour exclure les Afro-Américains, malgré les 14e et 15e amendements garantissant leur droit de vote.`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"L'isoloir", m:`Dispositif sanctuarisant le vote comme opération individuelle, pour protéger l'électeur des pressions extérieures.`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"Le marché électoral (Schumpeter)", m:`Conception de la démocratie (1942) calquée sur l'économie de marché : la campagne met en concurrence des offres politiques ; l'élection devient un affrontement d'idées et de programmes.`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"La programmatisation des scrutins", m:`Le choix repose sur le programme plutôt que sur la personne ; l'élu est perçu comme l'exécutant des votants. Illustrée par Jules Guesde, « porte-programme » (Roubaix, 1893).`},
{t:"notion", th:"Citoyens · Le sens politique de l'élection", r:"La personnalisation du scrutin", m:`Paradoxalement, la démocratisation s'accompagne d'un retour de l'autorité incarnée (depuis le milieu du XXe s.) : besoin d'identification à un chef, « sociétés de l'image ».`},
{t:"auteur", th:"Citoyens · Le sens politique de l'élection", r:"Bernard Manin — « Principes du gouvernement représentatif »", m:`Analyse l'élection comme un mécanisme initialement aristocratique (sélection des « meilleurs »), distinct du tirage au sort démocratique.`},
{t:"auteur", th:"Citoyens · Le sens politique de l'élection", r:"Joseph Schumpeter (marché électoral, 1942)", m:`Théorise la démocratie comme un marché : les dirigeants se font concurrence pour obtenir le vote des citoyens, comme des entreprises sur un marché.`},
{t:"auteur", th:"Citoyens · Le sens politique de l'élection", r:"Georges Burdeau (personnalisation)", m:`Explique le retour de l'autorité incarnée par la lassitude envers la délibération parlementaire et par des « sociétés de l'image » privilégiant l'identification à un leader.`},
{t:"auteur", th:"Citoyens · Le sens politique de l'élection", r:"Jules Guesde — le « porte-programme » (1893)", m:`À Roubaix, se présente non sur son nom mais comme le porte-programme du Parti ouvrier : illustre le passage du vote de personne au vote de programme.`},
{t:"date", th:"Citoyens · Le sens politique de l'élection", r:"1848 — proclamation du suffrage universel", m:`L'élection change de sens : elle appartient à tous les citoyens sans condition de fortune et devient l'expression de la volonté souveraine du corps électoral (et non plus la simple désignation d'un notable).`},

/* ============================================================
   8. CITOYENS · LES MODES DE SCRUTIN
   ============================================================ */
{t:"notion", th:"Citoyens · Les modes de scrutin", r:"Le mode de scrutin", m:`Méthode de conversion des voix en sièges. Il ne concerne que l'élection d'une assemblée (plusieurs sièges), pas l'élection d'une seule personne (ex. le Président).`},
{t:"notion", th:"Citoyens · Les modes de scrutin", r:"Les 4 variables d'un scrutin", m:`(1) la circonscription (échelle du vote) ; (2) le nombre de sièges (uninominal / plurinominal ou de liste) ; (3) le nombre de tours ; (4) la règle de conversion (majoritaire / proportionnelle).`},
{t:"notion", th:"Citoyens · Les modes de scrutin", r:"Le scrutin majoritaire", m:`Les sièges vont à celui qui obtient le plus de voix. Favorise l'efficacité gouvernementale et le bipartisme, mais « gâche » les voix portées sur les perdants et amplifie l'écart voix/sièges.`},
{t:"notion", th:"Citoyens · Les modes de scrutin", r:"La représentation proportionnelle (RP)", m:`Les sièges sont répartis selon le pourcentage de voix. Favorise la représentativité et le pluralisme (protège les petits partis) mais risque l'instabilité.`},
{t:"notion", th:"Citoyens · Les modes de scrutin", r:"Le scrutin majoritaire uninominal à deux tours (France, AN)", m:`Le « scrutin d'arrondissement » des élections législatives françaises. Exception européenne, partagée seulement avec le R-U (à un tour) et certains pays baltes.`},
{t:"notion", th:"Citoyens · Les modes de scrutin", r:"Le vote utile", m:`Pour ne pas « gâcher » sa voix, l'électeur délaisse son candidat de préférence (vote d'adhésion) au profit du mieux placé (vote stratégique). Effet mécanique du scrutin majoritaire.`},
{t:"notion", th:"Citoyens · Les modes de scrutin", r:"Le seuil de représentativité", m:`Minimum de voix (ex. 5 % ou 10 %) à franchir pour obtenir des sièges en RP. Protège les grands partis (européennes : 38 listes, mais 7 seulement franchissent le seuil de 5 %).`},
{t:"notion", th:"Citoyens · Les modes de scrutin", r:"La prime majoritaire", m:`Attribution de sièges « bonus » à la liste arrivée en tête, pour garantir une majorité (utilisée aux élections municipales).`},
{t:"notion", th:"Citoyens · Les modes de scrutin", r:"Le panachage", m:`Possibilité, en liste ouverte, pour l'électeur de rayer ou d'ajouter des noms. À distinguer du vote préférentiel (Irlande), qui permet de classer les candidats d'une liste.`},
{t:"notion", th:"Citoyens · Les modes de scrutin", r:"Représentation vs représentativité", m:`La représentation est un concept juridique (délégation du pouvoir de vouloir pour la Nation) ; la représentativité est une exigence sociologique de ressemblance (l'assemblée « miroir » de la société). La RP vise la « représentation-ressemblance ».`},
{t:"notion", th:"Citoyens · Les modes de scrutin", r:"Le mandat libre (non impératif)", m:`Le représentant n'est pas juridiquement lié par les promesses faites à ses électeurs : la ressemblance sociologique ne garantit donc pas la loyauté politique une fois le siège obtenu.`},
{t:"notion", th:"Citoyens · Les modes de scrutin", r:"L'« absolutisme majoritaire »", m:`Pratique de la Ve République où une majorité absolue (50 % + 1 siège) permet de gouverner « à marche forcée », sans chercher de compromis avec l'opposition.`},
{t:"notion", th:"Citoyens · Les modes de scrutin", r:"La tripolarisation (depuis 2022)", m:`Assemblée fragmentée en trois blocs (macronie, gauches/NFP, RN). Le scrutin majoritaire n'aboutit plus à une majorité absolue : assemblée bloquée, gouvernement minoritaire, absence de culture du compromis.`},
{t:"auteur", th:"Citoyens · Les modes de scrutin", r:"Montesquieu — « De l'esprit des lois »", m:`Souligne déjà que la modalité du suffrage (le mode de scrutin) est essentielle à la République.`},
{t:"auteur", th:"Citoyens · Les modes de scrutin", r:"Léon Gambetta — « un miroir brisé » (1881)", m:`Critique du scrutin d'arrondissement (iniquité géographique favorisant les zones rurales) : « un miroir brisé où la France ne reconnaît pas sa propre image ». [Note : graphié « Vendetta » dans le cours.]`},
{t:"auteur", th:"Citoyens · Les modes de scrutin", r:"Aristide Briand — les « mares stagnantes » (1909)", m:`Dénonce le clientélisme du scrutin majoritaire d'arrondissement, qui favoriserait une oligarchie locale et la corruption.`},
{t:"date", th:"Citoyens · Les modes de scrutin", r:"Le système mixte de 1919-1928", m:`Scrutin de liste départemental mêlant majorité et proportionnelle : produit la « Chambre bleu horizon » (droite, 1919) puis le « Cartel des gauches » (1924). Jugé non concluant, retour au majoritaire en 1927.`},
{t:"date", th:"Citoyens · Les modes de scrutin", r:"Les apparentements (1951)", m:`Sous la IVe Rép. : si des listes alliées obtiennent la majorité absolue, elles raflent tous les sièges. Favorise le centre au détriment des communistes et des gaullistes ; discrédite la RP.`},
{t:"date", th:"Citoyens · Les modes de scrutin", r:"Le « coup » de 1985-1986", m:`Mitterrand instaure la RP départementale (seuil 5 %) pour limiter la défaite annoncée du PS. Effet : première percée historique du FN (35 députés). Système supprimé dès 1986.`},
{t:"date", th:"Citoyens · Les modes de scrutin", r:"Distorsions voix/sièges : 2002 & 2017", m:`Effet amplificateur du scrutin majoritaire : en 2002, l'UMP obtient 61 % des sièges avec 33 % des voix (1er tour) ; en 2017, LREM décroche 54 % des sièges avec 28 % des voix.`},
{t:"date", th:"Citoyens · Les modes de scrutin", r:"2024 — le « Front républicain »", m:`Stratégie de désistement au second tour des législatives contre le RN. Relance le débat sur la proportionnelle (résolution du Sénat du 30 janvier 2025).`},

/* ============================================================
   9. CITOYENS · LA PARTICIPATION INSTITUTIONNELLE
   ============================================================ */
{t:"notion", th:"Citoyens · La participation institutionnelle", r:"Le référendum", m:`Consultation du corps électoral pour valider un objet précis ou adopter un texte (et non choisir une personne). Portée décisionnelle contraignante. Étym. lat. : « ce qui doit être rapporté ».`},
{t:"notion", th:"Citoyens · La participation institutionnelle", r:"Le plébiscite", m:`Variante « césariste » du référendum : invite l'électeur à renouveler sa confiance à un chef plutôt qu'à valider un projet. Dérive observée sous les deux Napoléon.`},
{t:"notion", th:"Citoyens · La participation institutionnelle", r:"L'initiative populaire", m:`Modalité où une fraction du corps électoral déclenche elle-même le référendum (courante en Italie et en Suisse). N'existe pas sous cette forme pure en France.`},
{t:"notion", th:"Citoyens · La participation institutionnelle", r:"Le référendum d'initiative partagée (RIP)", m:`Initiative mixte en France : soutien d'un cinquième des parlementaires + un dixième du corps électoral. L'initiative réelle restant aux parlementaires, aucune procédure n'a abouti à un scrutin.`},
{t:"notion", th:"Citoyens · La participation institutionnelle", r:"Le référendum révocatoire (recall)", m:`Mécanisme (inspiré des USA) permettant aux électeurs de révoquer un élu en cours de mandat s'ils ne sont plus satisfaits de son action.`},
{t:"notion", th:"Citoyens · La participation institutionnelle", r:"Le référendum local (art. 72-1, 2003)", m:`Depuis la révision constitutionnelle de 2003, permet aux collectivités territoriales de consulter les citoyens sur leurs compétences. Pratique aujourd'hui bien plus fréquente qu'au niveau national.`},
{t:"notion", th:"Citoyens · La participation institutionnelle", r:"« Démocratie semi-directe » (qualification discutée)", m:`Le référendum ne peut être qualifié de démocratie directe (le peuple ne s'auto-saisit pas) ; le terme « semi-directe » est aussi discuté, car l'élément de représentation demeure (le texte est rédigé par des instances représentatives).`},
{t:"notion", th:"Citoyens · La participation institutionnelle", r:"La désuétude du référendum", m:`Utilisé seulement 9 fois en 67 ans, plus depuis 2005. Causes : légitimité présidentielle (SUD + quinquennat), risque politique du désaveu, et traumatisme du rejet de 2005.`},
{t:"notion", th:"Citoyens · La participation institutionnelle", r:"Le Grand Débat National", m:`Réponse à la crise des « Gilets jaunes » : cahiers de doléances, plateforme en ligne (1,9 M de contributions), conférences avec citoyens tirés au sort. Critiqué comme très vertical et peu représentatif.`},
{t:"notion", th:"Citoyens · La participation institutionnelle", r:"La convention citoyenne", m:`Assemblée de citoyens tirés au sort pour éclairer la décision publique sur un sujet précis (information par experts → discussion → propositions). Reste purement consultative (pas de mandat électif).`},
{t:"notion", th:"Citoyens · La participation institutionnelle", r:"La Convention citoyenne pour le climat (2020-2021)", m:`149 propositions promises « sans filtre » par l'exécutif, mais beaucoup modifiées avant d'être intégrées à la loi Climat et Résilience (le fameux « filtre »).`},
{t:"notion", th:"Citoyens · La participation institutionnelle", r:"Le CESE", m:`Conseil économique, social et environnemental, revalorisé (loi organique du 15 juin 2020) comme pivot de la démocratie participative : organise les conventions citoyennes et centralise les pétitions (saisine à 150 000 signatures).`},
{t:"date", th:"Citoyens · La participation institutionnelle", r:"1969 — l'échec référendaire de De Gaulle", m:`Le rejet du référendum (régionalisation/Sénat) conduit au départ de De Gaulle : « spectre intimidant » qui dissuade encore les présidents d'y recourir.`},
{t:"date", th:"Citoyens · La participation institutionnelle", r:"2005 — rejet du traité constitutionnel européen", m:`Un référendum peut aboutir à une catastrophe électorale alors même que le gouvernement dispose d'une majorité parlementaire pour adopter le texte : « traumatisme » durable.`},
{t:"date", th:"Citoyens · La participation institutionnelle", r:"La Convention citoyenne sur la fin de vie", m:`Les citoyens se prononcent à 76 % en faveur d'une aide active à mourir ; un projet de loi est déposé mais la dissolution de l'Assemblée (2024) stoppe net le processus législatif.`},

/* ============================================================
   10. CITOYENS · LES MOBILISATIONS SPONTANÉES
   ============================================================ */
{t:"notion", th:"Citoyens · Les mobilisations spontanées", r:"La « fatigue démocratique »", m:`Faisceau d'indices d'une fragilisation du lien représentants/représentés : hausse de l'abstention, montée des populismes (« vrai peuple » vs « oligarchie »), actions directes (Gilets jaunes, assaut du Capitole).`},
{t:"notion", th:"Citoyens · Les mobilisations spontanées", r:"Crise ou tension structurelle ?", m:`La démocratie représentative est contestée dès sa naissance (boulangisme, années 30). Ce n'est pas une panne soudaine (« crise ») mais une tension structurelle : le système représentatif crée une distance (« aristocratie élective ») génératrice de frustration.`},
{t:"notion", th:"Citoyens · Les mobilisations spontanées", r:"La manifestation", m:`Moyen de contestation non institutionnalisé par excellence ; historiquement l'« arme des exclus » : exclus de droit (sans droit de vote) et exclus de fait (rejetant un système jugé monopolisé par une élite).`},
{t:"notion", th:"Citoyens · Les mobilisations spontanées", r:"Les 3 catégories de manifestations", m:`(1) Initiatrices (imposent un nouveau sujet : féminisme/IVG, écologie) ; (2) routinières (rappel de force syndicale, ex. 1er mai) ; (3) de crise politique (maintien/chute d'un régime, ex. 30 mai 1968).`},
{t:"notion", th:"Citoyens · Les mobilisations spontanées", r:"Les 3 rapports manifestation / pouvoir", m:`(1) Classique : faire plier le gouvernement (retraites 1995) ; (2) complément : relais d'une opposition parlementaire trop faible (retraites 2023, après le 49.3) ; (3) opposition radicale : contestation du système lui-même (Gilets jaunes, RIC).`},
{t:"notion", th:"Citoyens · Les mobilisations spontanées", r:"La « contre-démocratie » (Rosanvallon)", m:`« Démocratie de la défiance » : depuis les années 70, les citoyens ne cherchent plus seulement à désigner des gouvernants mais à exercer un pouvoir permanent de surveillance, de jugement et de contestation.`},
{t:"notion", th:"Citoyens · Les mobilisations spontanées", r:"La violence symbolique", m:`Au-delà de la violence physique : effigies brûlées, tags dégradant les symboles du pouvoir. Elle n'est pas unilatérale — l'État l'exerce aussi (refus du compromis, mépris perçu).`},
{t:"notion", th:"Citoyens · Les mobilisations spontanées", r:"« L'Affaire du Siècle »", m:`Action en justice ayant abouti à la condamnation de l'État pour préjudice écologique : illustration de l'usage des libertés fondamentales (ici l'action en justice) pour contraindre le pouvoir.`},
{t:"auteur", th:"Citoyens · Les mobilisations spontanées", r:"Pierre Rosanvallon — « La Contre-démocratie »", m:`Théorise la démocratie de la défiance : surveillance, empêchement et jugement deviennent des modes d'expression politique aussi importants que le vote.`},
{t:"date", th:"Citoyens · Les mobilisations spontanées", r:"Le boulangisme (fin XIXe s.)", m:`« Populisme avant l'heure » qui critique déjà le parlementarisme : preuve que la contestation de la démocratie représentative est aussi ancienne qu'elle.`},
{t:"date", th:"Citoyens · Les mobilisations spontanées", r:"Jean Jaurès et la ritualisation de la manifestation (1909)", m:`La manifestation passe d'un régime d'autorisation à un régime de simple déclaration (loi du 30 juin 1881) puis se « pacifie » et se ritualise, pour montrer que la classe ouvrière peut faire nombre de façon ordonnée.`},

/* ============================================================
   11. MÉDIATION · LA SOCIÉTÉ CIVILE
   ============================================================ */
{t:"notion", th:"Médiation · La société civile", r:"Les instances sociales de médiation", m:`Structures intermédiaires (associations, syndicats, groupes de pression, médias) qui agissent hors du système institutionnel. Deux fonctions : relais (peser collectivement) et tampon (protéger la société de l'omnipotence de l'État).`},
{t:"notion", th:"Médiation · La société civile", r:"La société civile", m:`Composante non politique de l'ordre social, située entre la sphère privée (famille) et la sphère étatique (gouvernement).`},
{t:"notion", th:"Médiation · La société civile", r:"La « société civile organisée »", m:`Structures permettant aux citoyens d'agir collectivement sans passer par les partis ou le vote : syndicats, associations, ONG, fondations, cultes, organisations caritatives.`},
{t:"notion", th:"Médiation · La société civile", r:"Les « libertés-relais » / « libertés-supports »", m:`Libertés (association, réunion, syndicale) qui permettent de dépasser le cadre individuel du bulletin de vote pour offrir une mobilisation permanente et collective, garantissant le pluralisme.`},
{t:"notion", th:"Médiation · La société civile", r:"L'individualisme (Tocqueville)", m:`Danger inhérent à l'égalisation des conditions : les citoyens égaux se replient sur leur sphère privée. D'où l'atomisation des rapports sociaux et la dilution du collectif.`},
{t:"notion", th:"Médiation · La société civile", r:"La « tyrannie de la majorité » / « despotisme démocratique »", m:`(Tocqueville) Risque qu'un pouvoir, au nom du plus grand nombre, devienne liberticide pour les minorités. Seul remède : l'existence d'instances sociales de médiation recréant du lien collectif.`},
{t:"notion", th:"Médiation · La société civile", r:"L'« individualisme étatiste » (Jaurès)", m:`La Révolution nie la dualité État/société : tout corps intermédiaire est une « société partielle » (Rousseau) corrompant la volonté générale. Interdire les groupements empêche la société de s'organiser contre l'État.`},
{t:"notion", th:"Médiation · La société civile", r:"L'associationnisme", m:`Doctrine cherchant à tempérer, voire concurrencer, l'autorité de l'État en permettant aux individus de s'unir. Comprend une branche libérale (Constant) et une branche de gauche/socialiste.`},
{t:"notion", th:"Médiation · La société civile", r:"Le mutualisme (Proudhon)", m:`Principal théoricien du socialisme libertaire : remplacer l'autorité de l'État par une organisation sociale faite d'associations ouvrières autogérées (anarchisme).`},
{t:"notion", th:"Médiation · La société civile", r:"La reconnaissance d'utilité publique (RUP)", m:`Pour avoir la pleine capacité (recevoir des legs, posséder un patrimoine), une association doit se placer « sous l'aile » de l'État (vs la « petite personnalité » des associations simplement déclarées). C'est le prix de l'influence.`},
{t:"notion", th:"Médiation · La société civile", r:"Le contrat d'engagement républicain (2021)", m:`Issu de la « loi séparatisme » : les associations doivent le signer (respect des principes de la République) pour obtenir des subventions publiques. Forme moderne d'allégeance, parfois utilisée pour censurer.`},
{t:"notion", th:"Médiation · La société civile", r:"La désyndicalisation", m:`Effondrement du taux de syndiqués (de 30 % à moins de 10 % des salariés) ; 2/3 des Français se défient des syndicats. Causes : individualisation du travail, mondialisation, dissolution de la « lutte des classes ».`},
{t:"notion", th:"Médiation · La société civile", r:"L'État « instituteur du social » (Rosanvallon)", m:`L'État reprend la main sur la société civile, reléguant les syndicats à un rôle purement consultatif (ex. réformes des retraites).`},
{t:"auteur", th:"Médiation · La société civile", r:"Alexis de Tocqueville — « De la démocratie en Amérique »", m:`« L'art de l'association est la science mère des sociétés démocratiques » : s'associer perfectionne les facultés humaines et protège contre l'isolement et la tyrannie de la majorité.`},
{t:"auteur", th:"Médiation · La société civile", r:"John Locke", m:`Premier à séparer nettement l'État de la société : l'État n'est qu'un mandataire qui reçoit la confiance de la société ; si cette confiance disparaît, il perd sa légitimité.`},
{t:"auteur", th:"Médiation · La société civile", r:"Pierre-Joseph Proudhon", m:`Théoricien du mutualisme et du socialisme libertaire : substituer aux pouvoirs publics une fédération d'associations ouvrières autogérées.`},
{t:"auteur", th:"Médiation · La société civile", r:"Ernest Duvergier de Hauranne", m:`Compare France et Angleterre : malgré l'absence de suffrage universel, l'Angleterre est une démocratie plus forte car sa société civile constitue un contre-pouvoir structurant.`},
{t:"texte", th:"Médiation · La société civile", r:"Le décret d'Allarde (mars 1791)", m:`Supprime les corporations de métiers : libère l'économie (liberté du commerce) et détruit les structures sociales de l'Ancien Régime.`},
{t:"texte", th:"Médiation · La société civile", r:"La loi Le Chapelier (juin 1791)", m:`Interdit aux membres d'une même profession de se réunir pour défendre leurs « prétendus intérêts communs ». « Il n'y a plus que l'intérêt particulier de chaque individu et l'intérêt général. »`},
{t:"texte", th:"Médiation · La société civile", r:"Article 291 du Code pénal de 1810", m:`Interdit toute association de plus de 20 personnes sans autorisation préalable du gouvernement : la société civile est mise sous tutelle préfectorale pendant tout le XIXe s.`},
{t:"texte", th:"Médiation · La société civile", r:"La loi de 1884 (Waldeck-Rousseau)", m:`Reconnaît la liberté syndicale : fin de l'interdiction de se coaliser pour défendre des intérêts professionnels.`},
{t:"texte", th:"Médiation · La société civile", r:"La loi du 1er juillet 1901 (associations)", m:`Passage d'un régime d'autorisation (bon vouloir du préfet) à un régime de déclaration : la liberté d'association devient le « cadre général » de la vie collective.`},
{t:"texte", th:"Médiation · La société civile", r:"La loi du 24 août 2021 (« loi séparatisme »)", m:`Dote l'État de leviers contre le séparatisme religieux. Instaure notamment le contrat d'engagement républicain conditionnant les subventions.`},
{t:"date", th:"Médiation · La société civile", r:"Les accords de Matignon (1936)", m:`« Âge d'or » du syndicalisme partenaire de l'État : conventions collectives, affirmation de la liberté syndicale, hausse des bas salaires, semaine de 40 h, congés payés.`},
{t:"date", th:"Médiation · La société civile", r:"Les accords de Grenelle (1968)", m:`Second « âge d'or » du syndicalisme : augmentation du salaire minimum de 35 %.`},
{t:"date", th:"Médiation · La société civile", r:"Soulèvements de la Terre / Quirittas (dissolutions)", m:`Armes politiques de l'État contre les collectifs jugés subversifs : la dissolution des Soulèvements de la Terre est annulée par le CE (faute de violence caractérisée), celle de Quirittas confirmée (haine, atteinte à la forme républicaine).`},

/* ============================================================
   12. MÉDIATION · L'OPINION PUBLIQUE & LES MÉDIAS
   ============================================================ */
{t:"notion", th:"Médiation · L'opinion publique & les médias", r:"L'opinion publique", m:`Force « diffuse » de la vie politique : inorganisée (pas de siège, de statuts ni de porte-parole) et mobile. Son caractère anonyme fait paradoxalement sa puissance (la voix du « grand nombre »).`},
{t:"notion", th:"Médiation · L'opinion publique & les médias", r:"Définition de Stoetzel", m:`« Un ensemble de jugements sur des problèmes actuels auxquels adhère une grande partie des membres d'une société. » Intègre deux éléments : le jugement (prise de position) et la communication.`},
{t:"notion", th:"Médiation · L'opinion publique & les médias", r:"L'« ère du secret » (Ancien Régime)", m:`L'opinion est occulte et élitiste, confinée aux salons et académies, limitée par l'illettrisme et la censure royale. L'opinion subversive doit se cacher (littérature, théâtre — ex. Beaumarchais emprisonné).`},
{t:"notion", th:"Médiation · L'opinion publique & les médias", r:"Le délit de « mauvais esprit » (Restauration)", m:`On punit non un acte mais une intention/tendance jugée subversive envers le Roi ou l'Autel. Preuve que l'opinion est devenue le socle de la légitimité : « qui contrôle l'opinion contrôle le pays ».`},
{t:"notion", th:"Médiation · L'opinion publique & les médias", r:"Le journalisme comme « ascenseur politique »", m:`Sous la Monarchie de Juillet, on acquiert sa légitimité par sa plume (ex. Adolphe Thiers), sans être né dans l'aristocratie. Le journaliste devient un acteur politique (au sens de Weber), auxiliaire du personnel politique.`},
{t:"notion", th:"Médiation · L'opinion publique & les médias", r:"L'opinion « médiatisée »", m:`L'opinion est rarement spontanée : l'information passe par un intermédiaire (le média) qui la met en forme. Ex. : la radio-TV (ORTF) longtemps contrôlée par le pouvoir « pour garantir l'ordre public ».`},
{t:"notion", th:"Médiation · L'opinion publique & les médias", r:"La concentration des médias", m:`Passage (années 80) du monopole d'État à une concentration entre grands groupes industriels (ex. Bolloré, Arnault), menaçant le pluralisme et l'indépendance des journalistes. Régulation (difficile) par l'ARCOM.`},
{t:"notion", th:"Médiation · L'opinion publique & les médias", r:"La distorsion algorithmique", m:`Le numérique crée un « effet grossissant » : une minorité très active peut saturer l'espace numérique et donner l'illusion d'être l'opinion majoritaire.`},
{t:"notion", th:"Médiation · L'opinion publique & les médias", r:"Les « chambres d'écho » (vs délibération)", m:`Sur les réseaux sociaux, on observe une juxtaposition de monologues entre gens déjà d'accord, à rebours de la délibération (échange et confrontation dans un espace public) au sens de Habermas.`},
{t:"notion", th:"Médiation · L'opinion publique & les médias", r:"L'atomisation de l'opinion", m:`Au lieu d'un sentiment collectif cohérent, l'opinion s'émiette en une multitude de fragments individuels, rendant tout consensus de plus en plus difficile.`},
{t:"auteur", th:"Médiation · L'opinion publique & les médias", r:"Jean Stoetzel", m:`Pionnier des sondages en France ; propose une définition de l'opinion publique combinant jugement sur l'actualité et communication entre individus.`},
{t:"auteur", th:"Médiation · L'opinion publique & les médias", r:"Jürgen Habermas", m:`L'opinion publique naît de la délibération : l'échange et la confrontation des arguments dans un espace public. Les réseaux sociaux fragilisent cet idéal (monologues, chambres d'écho).`},
{t:"auteur", th:"Médiation · L'opinion publique & les médias", r:"Adolphe Thiers (l'ascension par la plume)", m:`Exemple du journaliste devenu homme d'État : illustre que, sous la Monarchie de Juillet, la presse devient un « ascenseur politique » indépendant de la naissance.`},
{t:"texte", th:"Médiation · L'opinion publique & les médias", r:"Article 11 de la DDHC (1789)", m:`Consacre la liberté de communication des pensées et des opinions (liberté de la presse) : brise le monopole de la parole d'État et permet à la société de surveiller ses élus.`},
{t:"texte", th:"Médiation · L'opinion publique & les médias", r:"La loi du 29 juillet 1881 (liberté de la presse)", m:`Texte fondateur : libère la presse de toute autorisation préalable et de tout cautionnement. Avec l'instruction obligatoire et les rotatives, la presse devient le premier véritable « mass média ».`},
{t:"date", th:"Médiation · L'opinion publique & les médias", r:"« J'accuse… ! » de Zola (1898)", m:`Illustre le nouveau pouvoir de la presse : mobiliser l'opinion contre l'État et l'armée. La presse n'est plus un simple relais mais un acteur souverain.`},
{t:"date", th:"Médiation · L'opinion publique & les médias", r:"La Gazette de Théophraste Renaudot (1631)", m:`Organe quasi-officiel sous l'Ancien Régime : le pouvoir royal tente de contrôler l'information à une époque où l'opinion est confinée aux élites.`},
{t:"date", th:"Médiation · L'opinion publique & les médias", r:"WikiLeaks (le numérique brise le monopole)", m:`Diffusion de données brutes échappant à la censure étatique et aux choix éditoriaux des médias traditionnels : symbole de la fin du monopole des « gardiens du temple » (journalistes, éditeurs).`}

];
