/* =====================================================================
   QCM — Introduction to UK Public Law (Peggy Ducoulombier)
   Format de l'annale (Session 1, 2025/2026) : QCM à RÉPONSE UNIQUE,
   40 questions en 1 h, barème +0,5 / 0 / 0 (pas de point négatif).

   Chaque question :
     th : thème (= chapitre du cours)
     q  : énoncé
     o  : options (2 à 4)
     a  : index (0-based) de la BONNE réponse dans « o »
     e  : explication (corrigé)
     f  : 1 = ordre des options figé (ne pas mélanger) — utilisé pour Vrai/Faux
          et pour les questions de l'annale (afin de coller au sujet réel)
     an : 1 = question issue de l'annale (badge 📜)

   ⚠️ Les réponses des questions d'annale ont été déterminées d'après le cours,
   pas d'après les croix de la copie scannée (l'étudiant·e s'était trompé·e
   sur plusieurs). Quelques-unes (Q1, Q10, Q30) portent sur des réformes
   récentes — à recouper avec le corrigé officiel si tu l'obtiens.
   ===================================================================== */

window.QCM_THEMES = [
  "The UK Constitution",
  "Parliamentary Supremacy",
  "The Rule of Law",
  "Separation of Powers",
  "Devolution",
  "The UK Parliament",
  "The Crown & the Government"
];

window.QCM = [

/* ============ QUESTIONS D'ANNALE (Session 1, 2025/2026) ============ */
{th:"Devolution", an:1, f:1,
 q:"Challenges to bills of the Scottish Parliament on the basis of section 33 of the Scotland Act are limited to the traditional grounds for judicial review.",
 o:["True","False"], a:1,
 e:"Section 33 lets the Law Officers refer a Bill to the Supreme Court on the question of legislative competence (reserved matters, Convention rights, etc.). That is distinct from — and not limited to — the traditional grounds of judicial review (illegality, irrationality, procedural impropriety)."},

{th:"The UK Constitution", an:1, f:1,
 q:"Which of the following statements is correct?",
 o:["Institutional writers are a source of the UK constitution.",
    "Constitutional conventions are legal sources of the UK constitution.",
    "Constitutional law is made of legal sources regarding constitutional matters and of constitutional conventions.",
    "The sources of the UK constitution are statutes and common law only."],
 a:0,
 e:"Works of authority / institutional writers (Dicey, Bagehot…) are a recognised, if minor, source of the UK constitution. Conventions are non-legal (political) sources, not enforced by courts (B is wrong); the sources also include the prerogative and works of authority (D is wrong)."},

{th:"The UK Parliament", an:1, f:1,
 q:"Money bills are introduced in the House of Lords, because of its non-elected character and thus independent nature.",
 o:["True","False"], a:1,
 e:"Money bills are introduced in the House of Commons — the elected chamber — under its financial privilege (Art. 4 Bill of Rights 1689). The Lords may delay a money bill by at most one month (Parliament Act 1911)."},

{th:"The Crown & the Government", an:1, f:1,
 q:"The King is required by Statute Law to grant Royal Assent to a bill adopted by both Houses of Parliament.",
 o:["False","True"], a:0,
 e:"Royal Assent is governed by constitutional convention (and is a prerogative act), not by statute. By convention the monarch always grants it — Royal Assent has not been refused since 1708."},

{th:"Devolution", an:1, f:1,
 q:"The Senedd Cymru (Members and Elections) Act 2024…",
 o:["decreases the number of members to 90, changes the voting system to proportional representation, increases the length of the mandate of the Senedd to 5 years.",
    "increases the number of members to 96, changes the voting system to proportional representation, decreases the length of the mandate of the Senedd to 4 years.",
    "decreases the number of members to 96, changes the voting system to the first past the post system, increases the length of the mandate of the Senedd to 5 years.",
    "increases the number of members to 92, changes the voting system to proportional representation, increases the length of the mandate of the Senedd to 5 years."],
 a:1,
 e:"The Act increases the Senedd from 60 to 96 members, introduces a fully proportional closed-list system, and provides for ordinary general elections every 4 years (from 2026)."},

{th:"The UK Constitution", an:1, f:1,
 q:"The UK constitution is the superior law of the land as the UK Supreme Court enjoys the power to declare invalid legislation incompatible with it.",
 o:["True","False"], a:1,
 e:"Parliamentary sovereignty means no law is higher than an Act of Parliament; the UK Supreme Court cannot invalidate primary legislation. Under s.4 HRA it may only issue a declaration of incompatibility, which does not affect the validity of the Act."},

{th:"Separation of Powers", an:1, f:1,
 q:"The head of the judiciary in England and Wales is…",
 o:["The Lord Advocate.","The Lord Chancellor.","The Lord of appeal in ordinary.","The Lord Chief Justice."],
 a:3,
 e:"Since the Constitutional Reform Act 2005, the Lord Chief Justice is Head of the Judiciary of England and Wales (a role formerly held by the Lord Chancellor). The Lord Advocate is a Scottish officer; the Lords of Appeal in Ordinary were replaced by the Supreme Court."},

{th:"The UK Parliament", an:1, f:1,
 q:"The Parliament Acts apply to bills introduced in the House of Lords.",
 o:["True","False"], a:1,
 e:"The Parliament Acts 1911 & 1949 let the House of Commons obtain Royal Assent without the Lords' consent; they apply to public bills originating in the Commons, not to bills introduced in the Lords."},

{th:"Devolution", an:1, f:1,
 q:"Who is the Scottish Government legal adviser?",
 o:["The Advocate General for Scotland.","The Secretary of State for Scotland.","The Lord Advocate.","The Counsel for Scotland."],
 a:2,
 e:"The Lord Advocate is the chief legal adviser to the Scottish Government. The Advocate General for Scotland advises the UK Government on Scots law; the Secretary of State for Scotland is a UK minister."},

{th:"The UK Parliament", an:1, f:1,
 q:"The Representation of the People bill seeks to extend the right to vote in England, Wales and Scotland to individuals aged 16 and above.",
 o:["True","False"], a:1,
 e:"The announced 'votes at 16' reform lowers the voting age for UK parliamentary elections across the whole United Kingdom — including Northern Ireland — so a statement limited to England, Wales and Scotland is inaccurate. (À recouper avec le corrigé officiel.)"},

{th:"The UK Parliament", an:1, f:1,
 q:"Which of the following statements most accurately describes what the Salisbury convention entails?",
 o:["That the House of Lords will not defeat Government bills seeking to implement manifesto commitments.",
    "That Money bills start their life in the House of Lords.",
    "That judges sever all links with political parties when appointed.",
    "That the UK Parliament will refrain from legislating on devolved matters without the consent of the devolved Parliament."],
 a:0,
 e:"The Salisbury(-Addison) Convention: the Lords will not defeat at second reading a Government bill that implements a manifesto commitment. (D describes the Sewel Convention.)"},

{th:"The UK Parliament", an:1, f:1,
 q:"Which of the following statements most accurately defines what a Private Member's bill is?",
 o:["A bill affecting the general public but with a significant impact on specific individuals or groups.",
    "A bill relating to a matter of individual, corporate or local interest and changing the law as it applies to these specific individuals or organisations.",
    "A bill introduced in Parliament by a member of the Government.",
    "A bill introduced in Parliament by a backbencher."],
 a:3,
 e:"A Private Member's bill is a public bill introduced by a backbencher (not a government minister). Option B describes a 'private bill' (local/personal interest); C describes a government bill."},

{th:"The Crown & the Government", an:1, f:1,
 q:"The Dissolution and Calling of Parliament Act 2022 does not prevent Courts from ruling on the Prime Minister's decision to dissolve Parliament, as this is a justiciable issue.",
 o:["False","True"], a:0,
 e:"False. Section 3 of the DCPA 2022 (the 'ouster clause') revives the prerogative of dissolution and makes its exercise non-justiciable — the courts may not review the decision to dissolve Parliament."},

{th:"Parliamentary Supremacy", an:1, f:1,
 q:"In the case of HS2, it was suggested that…",
 o:["an EU directive could impose article 9 of the Bill of Rights to be set aside.",
    "the EC Act 1972 required all conflicting domestic legislation to be set aside.",
    "the constitutional status of the EC Act 1972 did not ensure primacy of EU Law in all circumstances.",
    "the Factortame case could be applied to solve the legal issue raised by the case."],
 a:2,
 e:"In R (HS2 Action Alliance) v Secretary of State for Transport (2014), the Supreme Court suggested there may be a hierarchy of constitutional statutes/principles: the ECA 1972 did not necessarily require fundamental constitutional principles (e.g. Art. 9 Bill of Rights) to be set aside, so EU-law primacy was not guaranteed in all circumstances."},

{th:"Parliamentary Supremacy", an:1, f:1,
 q:"In the case of Hirst v the UK n°2, it was ruled that…",
 o:["the United Kingdom had to give all prisoners the right to vote.",
    "the United Kingdom was in breach of article 3 of the First additional protocol to the ECHR.",
    "the United Kingdom had to issue a declaration of incompatibility regarding its legislation on the franchise to the House of Commons elections.",
    "the United Kingdom was in breach of the EU Charter of fundamental rights."],
 a:1,
 e:"Hirst v UK (No 2) (2005, ECtHR Grand Chamber): the blanket ban on convicted prisoners voting breached Article 3 of Protocol No. 1 (right to free elections). It did not require votes for ALL prisoners (states keep a margin of appreciation); a 'declaration of incompatibility' is a domestic HRA remedy, not an ECtHR ruling."},

{th:"Devolution", an:1, f:1,
 q:"A devolved system does not preserve the powers of the central Parliament in relation to all matters, whether devolved or reserved.",
 o:["True","False"], a:1,
 e:"False. Unlike federalism, devolution preserves the UK Parliament's legal sovereignty over ALL matters — devolved and reserved (Scotland Act 1998, s.28(7)). Westminster can still legislate on devolved matters; the Sewel Convention is only a political restraint."},

{th:"Devolution", an:1, f:1,
 q:"Which of the following statements is true? On the basis of section 35 of the Scotland Act…",
 o:["The Lord Advocate can refer a devolution issue to the Supreme Court.",
    "The Presiding officer of the Scottish Parliament may refuse to send a bill of the Scottish Parliament for Royal assent if he/she has reasonable grounds to believe the bill is outside the legislative competence of the Parliament.",
    "The Attorney General may veto a decision by a Scottish minister if he/she believes the action to be contrary to the interest of the UK Government.",
    "The Secretary of State for Scotland may veto a Scottish Parliament bill which he/she has reasonable grounds to believe would have an adverse effect on the operation of the law as it applies to reserved matters."],
 a:3,
 e:"Section 35 of the Scotland Act 1998 lets the Secretary of State make an order preventing a Bill being submitted for Royal Assent if there are reasonable grounds to believe it would be incompatible with international obligations/defence/national security, or would adversely affect the operation of the law as it applies to reserved matters (power used against the Gender Recognition Reform (Scotland) Bill, 2023)."},

{th:"The UK Parliament", an:1, f:1,
 q:"The House of Lords (Hereditary Peers) Act 2026…",
 o:["Replaces Hereditary peers with Life Peers at the next Parliamentary session.",
    "Removes Hereditary Peers from the House of Lords with immediate effect.",
    "Removes Hereditary Peers from the House of Lords from the next Parliamentary session onwards.",
    "Removes progressively Hereditary Peers from the House of Lords by not replacing them when they die or leave the House."],
 a:2,
 e:"The House of Lords (Hereditary Peers) Bill removes the remaining 92 hereditary peers; they cease to be members at the end of the parliamentary session in which the Act is passed (i.e. from the next session). It is a clean removal, not a gradual phase-out by attrition. (À recouper avec le corrigé officiel.)"},

{th:"Parliamentary Supremacy", an:1, f:1,
 q:"According to section 19 of the Human Rights Act 1998,…",
 o:["the person introducing a bill before the House must be able to make a statement according to which he or she thinks that the bill is compliant with Convention Rights for the House to proceed with the bill.",
    "if the person introducing a bill before the House is unable to make a statement that the bill is compliant with Convention Rights, he or she may state that the Government still wishes the House to proceed with the bill.",
    "if the person introducing the bill before the House cannot state that the bill is compliant with Convention Rights, then the House must pass a resolution according to which, by a majority, it accepts to proceed with the bill.",
    "if the person introducing the bill cannot state that the bill is compliant with Convention Rights, the bill must be referred to the Supreme Court, for the Supreme Court to rule on the issue."],
 a:1,
 e:"S.19 HRA: before second reading the minister in charge of a bill must make EITHER a statement of compatibility with Convention rights, OR a statement that, although unable to do so, the Government nevertheless wishes the House to proceed."},

{th:"Parliamentary Supremacy", an:1, f:1,
 q:"According to the Human Rights Act 1998, UK courts…",
 o:["must take into account any relevant ECtHR case-law.",
    "must only take into account relevant Grand chamber case-law.",
    "must refer a question to the ECtHR in case of doubt as to the compliance of the law with Convention Rights.",
    "are bound to follow ECtHR case-law."],
 a:0,
 e:"S.2 HRA requires courts to 'take into account' any relevant Strasbourg (ECtHR) case law — they must consider it but are not bound by it, and there is no preliminary-reference mechanism to the ECtHR."},

{th:"Separation of Powers", an:1, f:1,
 q:"Which Act reformed the House of Lords by removing the final appeal court from within the chamber?",
 o:["The Parliament Act 1911.","The Constitutional Reform Act 2005.","The House of Lords Act 1999.","The Supreme Court Act 1981."],
 a:1,
 e:"The Constitutional Reform Act 2005 created the UK Supreme Court (operational 2009), removing the Appellate Committee of the House of Lords (the final appeal court) from the legislative chamber."},

{th:"Devolution", an:1, f:1,
 q:"Which of the following statements is false?",
 o:["The validity of an Act of the Scottish Parliament is not affected by any invalidity in the proceedings of the Parliament leading to its enactment.",
    "Acts of the Scottish Parliament are amenable to challenge before the courts on certain grounds.",
    "Acts of the Scottish Parliament enacted with regard to reserved matters are invalid on the basis of section 29 of the Scotland Act 1998.",
    "Acts of the Scottish Parliament do not receive royal assent because the Scottish Parliament is not supreme."],
 a:3,
 e:"D is false: Acts of the Scottish Parliament DO receive Royal Assent (Scotland Act 1998, ss.28 & 32-33). A, B and C are true — in particular s.29 makes provisions relating to reserved matters 'not law' (outside competence)."},

{th:"Separation of Powers", an:1, f:1,
 q:"Which statute imposes a duty on ministers to uphold the independence of the judiciary?",
 o:["The Disqualification Act 1975.","The Freedom of Information Act 2000.","The Constitutional Reform Act 2005.","The Senior Courts Act 1981."],
 a:2,
 e:"Section 3 of the Constitutional Reform Act 2005 imposes a statutory duty on the Lord Chancellor and other ministers to uphold the continued independence of the judiciary and not to seek to influence judicial decisions."},

{th:"Parliamentary Supremacy", an:1, f:1,
 q:"Which of the following statements is true with regard to the Human Rights Act?",
 o:["It is impossible to interpret legislation in compliance with Convention Rights when there is no ambiguity in the law.",
    "Section 3 does not allow interpretation that goes against the grain of legislation.",
    "Courts must strive to interpret legislation in compliance with Convention Rights and if it is not possible, they must resort to a declaration of incompatibility.",
    "It is impossible for Parliament to disapply section 3 of the HRA in relation to a specific legislation."],
 a:2,
 e:"C describes the s.3 → s.4 scheme: courts must read legislation compatibly with Convention rights so far as possible (s.3, even without ambiguity), and only where that is impossible do they issue a declaration of incompatibility (s.4). (B is a tempting distractor — the 'against the grain' limit from Ghaidan — but C best states the overall obligation.)"},

{th:"Separation of Powers", an:1, f:1,
 q:"Which of the following is not a theoretical feature of the separation of powers doctrine?",
 o:["Everyone is governed by and equal under the law.",
    "The same persons should not form part of more than one of the three branches of the State.",
    "One body of government should not exercise the functions of another.",
    "One body of government should not unduly interfere with the work of another."],
 a:0,
 e:"Equality before the law is a feature of the RULE OF LAW, not of the separation of powers. B, C and D are the three classic strands of the separation-of-powers doctrine."},

{th:"The UK Parliament", an:1, f:1,
 q:"The position of Lord Speaker dates back to the 17th century.",
 o:["False","True"], a:0,
 e:"False. The office of Lord Speaker (presiding officer of the House of Lords) was created only in 2006, following the Constitutional Reform Act 2005 — previously the Lord Chancellor presided over the Lords."},

{th:"The UK Constitution", an:1, f:1,
 q:"Which of the following elements is not part of the Jennings test regarding constitutional conventions?",
 o:["What are the precedents for the rule?",
    "Do political actors feel bound by the rule?",
    "Did the Courts recognise the existence of the rule?",
    "Is there a reason for the rule?"],
 a:2,
 e:"Jennings's three-part test asks: (1) are there precedents? (2) do the actors believe they are bound? (3) is there a good reason for the rule? Judicial recognition is NOT part of it — conventions are non-legal and not enforced by courts."},

{th:"The Crown & the Government", an:1, f:1,
 q:"Which of the following statements is correct? Prerogative powers…",
 o:["are not subject to judicial review as opposed to statutory powers.",
    "are subject to judicial review in any circumstances.",
    "are subject to judicial review on procedural grounds only.",
    "are subject to judicial review provided that they are justiciable in nature."],
 a:3,
 e:"Since the GCHQ case (1985), prerogative powers are reviewable in principle — but only where their subject matter is justiciable. Some prerogatives (national security, foreign affairs, treaty-making, the armed forces, mercy) remain non-justiciable."},

{th:"The UK Constitution", an:1, f:1,
 q:"After IP day, the EU Charter of Fundamental Rights became part of Retained EU Law.",
 o:["True","False"], a:1,
 e:"False. Section 5(4) of the EU (Withdrawal) Act 2018 expressly provides that the EU Charter of Fundamental Rights is NOT part of retained (domestic) EU law after IP completion day (31 Dec 2020)."},

{th:"The Rule of Law", an:1, f:1,
 q:"Joseph Raz defends a substantive conception of the Rule of Law.",
 o:["True","False"], a:1,
 e:"False. Raz defends a FORMAL conception: the rule of law concerns the form of legal rules (prospective, clear, stable, open…) and is 'not to be confused with democracy, justice, equality or human rights' — i.e. not its substance."},

{th:"Devolution", an:1, f:1,
 q:"The Wales Act 2017 implements a conferred powers model of devolution for Wales.",
 o:["True","False"], a:1,
 e:"False. The Wales Act 2017 moved Wales from a conferred-powers model to a RESERVED-powers model (like Scotland), in force from April 2018, and renamed the legislature the Senedd."},

{th:"The UK Constitution", an:1, f:1,
 q:"The Retained EU Law (Revocation and Reform) Act 2023 had the effect of revoking all remaining retained EU law before the end of 2023.",
 o:["False","True"], a:0,
 e:"False. The planned 'sunset' of all retained EU law by end-2023 was dropped: the Act instead revoked only a listed schedule of instruments and renamed the rest 'assimilated law' from the end of 2023."},

{th:"The UK Parliament", an:1, f:1,
 q:"Which of the following statements accurately describes the function of the House of Commons select committees?",
 o:["To scrutinise amendments to public bills.",
    "To scrutinise the policies, administration and expenditure of Government departments.",
    "To propose new legislation.",
    "To select which MPs can ask a question during Prime Minister's question time."],
 a:1,
 e:"Departmental select committees scrutinise the policy, administration and expenditure of the Government departments they shadow. (Scrutinising bill amendments is the job of Public Bill Committees.)"},

{th:"The Crown & the Government", an:1, f:1,
 q:"The Parent Act is…",
 o:["the Act that established the Parliament of the United Kingdom following the Union with Ireland.",
    "the Act that devolved powers to the Scottish Parliament.",
    "the Act that regulates the rules of parenthood in the UK.",
    "the Act that delegates authority to a Minister to enact law."],
 a:3,
 e:"In the context of delegated legislation, the 'parent' (or enabling/empowering) Act is the primary Act of Parliament that confers power on a minister to make secondary legislation."},

{th:"Separation of Powers", an:1, f:1,
 q:"What is the principle laid down in article 9 of the Bill of Rights?",
 o:["That the House of Lords must approve bills seeking to extend the life of Parliament beyond 5 years.",
    "That the levying of money without the consent of Parliament is illegal.",
    "That debates in Parliament cannot be questioned in Courts.",
    "That the Scottish Parliament cannot be revoked without the support of the majority of the Scottish People."],
 a:2,
 e:"Article 9 of the Bill of Rights 1689 protects parliamentary privilege: freedom of speech and proceedings in Parliament 'ought not to be impeached or questioned in any court'. (B states the principle of Article 4 — no taxation without consent.)"},

{th:"The Crown & the Government", an:1, f:1,
 q:"In the case of R (Privacy International) v. Investigatory Powers Tribunal, the majority of the Supreme Court held that…",
 o:["there was no contradiction with EU Law in relation to the ban on the prisoners' right to vote.",
    "it was legal for the Attorney General to overrule the decision of the Tribunal regarding disclosure of information, as this was the clear intent of Parliament.",
    "the High Court was not precluded from reviewing the decision of the Tribunal as to errors of law.",
    "it was unlawful for the Prime Minister to advise the Queen to prorogue Parliament for several weeks."],
 a:2,
 e:"R (Privacy International) v IPT (2019): the majority held that the ouster clause did not exclude judicial review of the Tribunal's decisions for errors of law — the High Court was not precluded from reviewing them. (D describes Miller No 2 / Cherry.)"},

{th:"The UK Parliament", an:1, f:1,
 q:"Who is the person responsible for organising the Government's business in the House?",
 o:["The Speaker of the House","The Leader of the House","The Earl Marshal","The Whip"],
 a:1,
 e:"The Leader of the House (of Commons) is the minister responsible for arranging and announcing the Government's business and managing the House. The Whips enforce party discipline and attendance/voting."},

{th:"The UK Parliament", an:1, f:1,
 q:"On the basis of its financial privilege, Parliament can propose increases in taxation or public expenditure.",
 o:["True","False"], a:1,
 e:"False. Parliament must consent to all taxation and spending, but the right of financial INITIATIVE rests with the Government (the Crown): Parliament can only scrutinise and authorise what the Government proposes, not itself propose increases."},

{th:"The Crown & the Government", an:1, f:1,
 q:"What is the name given to a clause in a bill allowing primary legislation to be amended by secondary legislation?",
 o:["Edward VII clause","Elisabeth II clause","Henry VIII clause","Richard III clause"],
 a:2,
 e:"A 'Henry VIII clause' empowers ministers to amend or repeal primary legislation (an Act of Parliament) by secondary legislation — controversial as it transfers legislative power to the executive."},

{th:"The UK Parliament", an:1, f:1,
 q:"Which of the following statements most accurately describes what a Green Paper is?",
 o:["A consultation document produced by the Government to allow stakeholders to give feedback on its legislative proposals.",
    "A report published after a Royal Commission's inquiry.",
    "A policy document produced by the Government that sets out its proposals for future legislation.",
    "A document explaining to MPs the content of the various clauses of a bill laid before Parliament."],
 a:0,
 e:"A Green Paper is a consultation document setting out tentative proposals to invite feedback from stakeholders. (Option C describes a White Paper, which sets out firmer policy proposals for legislation.)"},

/* ============ THE UK CONSTITUTION ============ */
{th:"The UK Constitution", f:1,
 q:"The UK constitution is best described as…",
 o:["codified and rigid","uncodified, flexible and a 'patchwork'","entrenched in a single superior document","subordinate to EU law"],
 a:1,
 e:"Jowell & Oliver: the UK constitution is uncodified, flexible and a 'patchwork'. It fails all of Ridley's four criteria for a 'capital C' constitution."},

{th:"The UK Constitution",
 q:"What did Laws LJ establish in Thoburn v Sunderland City Council (2002)?",
 o:["Constitutional statutes can be impliedly repealed like any other statute",
    "Constitutional statutes can only be repealed by express words, not by implied repeal",
    "The ECA 1972 was struck down as unconstitutional",
    "Acts of Parliament are subject to constitutional review"],
 a:1,
 e:"Laws LJ distinguished constitutional from ordinary statutes: constitutional statutes (e.g. the ECA 1972) are immune from the doctrine of implied repeal and can be repealed only by express words."},

{th:"The UK Constitution",
 q:"That the UK is a 'dualist' state means that…",
 o:["treaties automatically become domestic law on ratification",
    "international law takes domestic effect only once transposed by an Act of Parliament",
    "domestic law always prevails before international courts",
    "the UK cannot ratify international treaties"],
 a:1,
 e:"In a dualist system, international and domestic law are separate; a treaty has domestic effect only once incorporated by statute (e.g. the ECHR via the Human Rights Act 1998)."},

{th:"The UK Constitution",
 q:"Which statement about the Brexit referendum of 23 June 2016 is correct?",
 o:["It was legally binding on Parliament",
    "52% voted Leave overall, but Scotland and Northern Ireland voted Remain",
    "All four nations voted Leave",
    "The UK left the EU on the day of the referendum"],
 a:1,
 e:"The referendum was consultative, not legally binding. 52% voted Leave overall, but Scotland (62%) and Northern Ireland (55.8%) voted Remain. The UK formally left on 31 January 2020."},

/* ============ PARLIAMENTARY SUPREMACY ============ */
{th:"Parliamentary Supremacy",
 q:"According to Dicey, parliamentary sovereignty means that Parliament…",
 o:["is bound by its predecessors",
    "can make or unmake any law, and no body may override its legislation",
    "is subordinate to the common law",
    "can be overruled by the courts"],
 a:1,
 e:"Dicey (1885): Parliament can make or unmake any law whatsoever; no person or body may set aside an Act of Parliament; and Parliament cannot bind its successors."},

{th:"Parliamentary Supremacy",
 q:"In Factortame (1990), the House of Lords held that UK courts could…",
 o:["strike down and annul the Merchant Shipping Act 1988",
    "'disapply' provisions of an Act of Parliament conflicting with directly effective EU law",
    "ignore EU law entirely",
    "refer the Act to the European Court of Human Rights"],
 a:1,
 e:"Following the ECJ reference, the courts could 'disapply' (suspend) provisions of the Merchant Shipping Act 1988 incompatible with directly effective EU law — not strike them down or declare them void."},

{th:"Parliamentary Supremacy", f:1,
 q:"Under section 4 of the Human Rights Act 1998, a declaration of incompatibility…",
 o:["invalidates the incompatible legislation",
    "does not affect the validity or continuing operation of the legislation",
    "can be issued by any court",
    "legally obliges Parliament to amend the law"],
 a:1,
 e:"A s.4 declaration of incompatibility does not affect the validity, continuing operation or enforcement of the provision; only superior courts may issue one, and Parliament is not legally bound to amend the law."},

{th:"Parliamentary Supremacy",
 q:"What does section 3 of the Human Rights Act 1998 require?",
 o:["Courts to treat ECtHR case law as binding precedent",
    "Legislation to be read compatibly with Convention rights so far as it is possible to do so",
    "Ministers to certify compatibility before introducing a bill",
    "The automatic repeal of incompatible legislation"],
 a:1,
 e:"S.3 requires legislation to be read and given effect compatibly with Convention rights 'so far as it is possible to do so' — even where there is no ambiguity (R v A; Ghaidan v Godin-Mendoza)."},

{th:"Parliamentary Supremacy",
 q:"Ghaidan v Godin-Mendoza (2004) shows that, under s.3 HRA, courts may…",
 o:["never depart from the words of a statute",
    "read words into legislation to make it Convention-compliant",
    "strike down incompatible statutes",
    "disregard Convention rights"],
 a:1,
 e:"Lord Nicholls: s.3 may require courts to depart from the enacting Parliament's intention and read in words — here the Rent Act 1977 was read to extend succession rights to same-sex partners."},

{th:"Parliamentary Supremacy",
 q:"The 'manner and form' debate concerns whether Parliament can…",
 o:["legislate retrospectively",
    "bind its successors as to the procedure or form (not content) of future legislation",
    "delegate law-making to ministers",
    "legislate with extra-territorial effect"],
 a:1,
 e:"Jennings's self-embracing view: Parliament can bind itself as to manner and form (not content). Wade's continuing view denies this. The EU Act 2011 'referendum lock' revived the debate (Bogdanor's paradox)."},

{th:"Parliamentary Supremacy",
 q:"According to Wade's 'continuing' theory of sovereignty…",
 o:["Parliament can redefine itself and bind its successors",
    "sovereignty is a political fact that only a 'revolution' could change",
    "Parliament is bound by the common law",
    "the courts, not Parliament, are sovereign"],
 a:1,
 e:"Wade: each Parliament is equally and continuously sovereign and cannot bind its successors; the ultimate rule of recognition rests on political fact and could change only by 'revolution' (contrast Jennings's self-embracing view)."},

/* ============ THE RULE OF LAW ============ */
{th:"The Rule of Law",
 q:"Which is one of Dicey's three elements of the rule of law?",
 o:["a codified constitution","equality before the ordinary law","a separate system of administrative courts","proportionality review"],
 a:1,
 e:"Dicey's three elements: legality, equality (equal subjection of all to the ordinary law — no separate droit administratif), and the common-law basis of the constitution."},

{th:"The Rule of Law",
 q:"Raz's conception of the rule of law is best described as…",
 o:["a substantive theory requiring respect for human rights",
    "a formal conception concerned with the form of law, not its content",
    "identical to democracy",
    "indifferent to the clarity of the law"],
 a:1,
 e:"Raz's principles (prospective, clear, stable, open law; independent judiciary; fair hearing) are formal: the rule of law concerns the form of legal rules and is 'not to be confused with democracy, justice, equality or human rights'."},

{th:"The Rule of Law",
 q:"In A v Secretary of State for the Home Department (2004) — the 'Belmarsh' case — the House of Lords held that…",
 o:["indefinite detention of foreign terror suspects was lawful",
    "indefinite detention of non-nationals breached Arts 5 and 14 ECHR",
    "all the detainees had to be deported",
    "the courts could strike down the Act"],
 a:1,
 e:"The Lords issued a declaration of incompatibility: indefinite detention of non-national suspects (ATCSA 2001, s.23) was disproportionate and discriminatory, breaching Arts 5 & 14 ECHR. Lord Hoffmann said the real threat to the nation came 'from laws such as these'."},

{th:"The Rule of Law",
 q:"Entick v Carrington (1765) is authority for the principle that…",
 o:["the executive may act unless expressly prohibited",
    "the government must point to specific legal authority to interfere with a citizen's rights or property",
    "the courts cannot review government action",
    "prerogative powers are unlimited"],
 a:1,
 e:"A foundational rule-of-law case: state officials may not interfere with a person's rights or property without positive legal authority (Dicey's principle of legality)."},

/* ============ SEPARATION OF POWERS ============ */
{th:"Separation of Powers",
 q:"Bagehot described the relationship between the UK executive and legislature as one of…",
 o:["strict separation","'close union, the nearly complete fusion'","total mutual independence","judicial supremacy"],
 a:1,
 e:"Bagehot: the 'efficient secret' of the constitution is the 'close union, the nearly complete fusion' of the executive and legislative powers (ministers sit in, and are accountable to, Parliament)."},

{th:"Separation of Powers",
 q:"Which reform was introduced by the Constitutional Reform Act 2005?",
 o:["the abolition of the House of Lords",
    "the creation of an independent UK Supreme Court and the reform of the Lord Chancellor",
    "the codification of the UK constitution",
    "the abolition of the monarchy"],
 a:1,
 e:"The CRA 2005 created the UK Supreme Court (operational 2009), reformed the Lord Chancellor (no longer head of the judiciary or a sitting judge) and created the Judicial Appointments Commission."},

{th:"Separation of Powers",
 q:"Montesquieu's theory of the separation of powers holds that the three functions of government should be…",
 o:["concentrated in one body for efficiency",
    "exercised by three distinct bodies to prevent the abuse of power",
    "subordinate to the judiciary",
    "all exercised by the monarch"],
 a:1,
 e:"Montesquieu (The Spirit of the Laws, 1748): the legislative, executive and judicial functions should be in distinct hands to prevent abuse; absolute separation is neither possible nor desirable (checks and balances)."},

{th:"Separation of Powers",
 q:"The maximum number of ministers who may sit in the House of Commons is…",
 o:["50","95","120","unlimited"],
 a:1,
 e:"The House of Commons Disqualification Act 1975 caps the number of ministers in the Commons at 95 — a limit on the executive's 'fusion' with the legislature."},

/* ============ DEVOLUTION ============ */
{th:"Devolution",
 q:"Which type of devolution involves the transfer of the power to enact primary legislation?",
 o:["administrative devolution","executive devolution","legislative devolution","fiscal devolution"],
 a:2,
 e:"Legislative devolution transfers the power to make primary legislation in certain fields (e.g. the Scottish Parliament). Executive devolution transfers only subordinate policy-making; administrative devolution is mere deconcentration."},

{th:"Devolution",
 q:"After R (Miller) v Secretary of State for Exiting the EU (2017), the Sewel Convention is…",
 o:["a legally enforceable rule",
    "a political convention that the courts cannot enforce",
    "a provision with full legal force since its codification",
    "binding on the Scottish Parliament"],
 a:1,
 e:"Although codified in s.28(8) Scotland Act 2016, Miller (2017) confirmed the Sewel Convention remains a political convention — courts cannot enforce it. Devolution is thus a political, not legal, limit on sovereignty."},

{th:"Devolution",
 q:"The 'West Lothian Question' refers to…",
 o:["whether Scotland should become independent",
    "Scottish/Welsh/NI MPs voting at Westminster on English-only matters while English MPs cannot vote on devolved matters",
    "the funding formula for the devolved governments",
    "the jurisdiction of the Supreme Court over devolution"],
 a:1,
 e:"Posed by Tam Dalyell: the anomaly that MPs from devolved nations can vote on English-only matters at Westminster, while English MPs have no say over devolved matters. 'EVEL' was a partial response (withdrawn in 2021)."},

{th:"Devolution", f:1,
 q:"Under the Northern Ireland Act 1998, Northern Ireland remains part of the UK…",
 o:["permanently and irrevocably",
    "until its electorate decides otherwise in a referendum",
    "until the UK Parliament decides otherwise",
    "until the Republic of Ireland consents"],
 a:1,
 e:"S.1 enshrines the 'principle of consent' from the Good Friday/Belfast Agreement: NI remains in the UK until a majority of its people, voting in a referendum, decide otherwise."},

{th:"Devolution",
 q:"Devolution differs from federalism because…",
 o:["devolved powers can never be legislated on by the centre",
    "the central Parliament retains legal sovereignty over all matters",
    "devolved legislatures have entrenched constitutional status",
    "the centre cannot create or abolish devolved bodies"],
 a:1,
 e:"In devolution the UK Parliament remains legally sovereign and could, in law, legislate on devolved matters or abolish the devolved bodies — unlike federalism, where regional powers are constitutionally entrenched."},

/* ============ THE UK PARLIAMENT ============ */
{th:"The UK Parliament",
 q:"Members of the House of Commons are elected by…",
 o:["closed-list proportional representation","the single transferable vote","first past the post","the additional member system"],
 a:2,
 e:"The 650 MPs are elected by First Past the Post: single-member constituencies, relative majority, one round."},

{th:"The UK Parliament", f:1,
 q:"Under the Parliament Act 1911, a 'money bill'…",
 o:["can be delayed by the Lords for up to one year",
    "may be delayed by the Lords for at most one month",
    "must be introduced in the House of Lords",
    "requires the consent of the monarch's prerogative"],
 a:1,
 e:"A money bill (certified by the Speaker) may be delayed by the Lords for no more than one month; it originates in the Commons under its financial privilege."},

{th:"The UK Parliament",
 q:"Collective ministerial responsibility means that…",
 o:["each minister is liable only for personal misconduct",
    "the Government must keep the confidence of the Commons and publicly present a united front",
    "ministers cannot be questioned in Parliament",
    "the Cabinet has legal powers of its own"],
 a:1,
 e:"Under collective responsibility the Government stands or falls together, publicly supports agreed policy, and must retain the confidence of the House of Commons (a lost confidence vote can bring it down)."},

{th:"The UK Parliament",
 q:"Under the Recall of MPs Act 2015, an MP's seat may be vacated by petition where the MP…",
 o:["loses a vote in the House",
    "receives a custodial sentence or is suspended for 21+ sitting days, and 10% of electors sign",
    "resigns from their political party",
    "is criticised by a select committee"],
 a:1,
 e:"A recall petition is triggered by certain conduct (a custodial sentence, suspension of 21+ sitting days, or false expenses claims); the seat is vacated if at least 10% of eligible electors sign it."},

/* ============ THE CROWN & THE GOVERNMENT ============ */
{th:"The Crown & the Government",
 q:"Which of the following is a personal (royal) prerogative of the Crown?",
 o:["declaring war","the appointment of the Prime Minister","issuing passports","making treaties"],
 a:1,
 e:"Personal prerogatives (exercised by the monarch, on convention) include appointing the PM, appointing/dismissing ministers, granting Royal Assent and dissolving Parliament. War, passports and treaties are executive prerogatives exercised by ministers."},

{th:"The Crown & the Government",
 q:"In R (Miller) v Secretary of State for Exiting the EU (2017), the Supreme Court held that…",
 o:["the Government could trigger Article 50 using the prerogative alone",
    "triggering Article 50 required prior statutory authorisation by Parliament",
    "the referendum result was legally binding",
    "the Sewel Convention was legally enforceable"],
 a:1,
 e:"Miller (2017): the Government could not use the prerogative to trigger Art. 50 TEU, because that would remove rights conferred by the ECA 1972; an Act of Parliament was required. The Court also confirmed Sewel is a non-legal convention."},

{th:"The Crown & the Government",
 q:"The GCHQ case (Council of Civil Service Unions v Minister for the Civil Service, 1985) established that…",
 o:["prerogative powers can never be judicially reviewed",
    "prerogative powers are reviewable in principle, subject to non-justiciable exceptions",
    "the prerogative is unlimited in national-security matters",
    "all prerogative powers derive from statute"],
 a:1,
 e:"Lord Scarman: a power is not immune from review merely because it derives from the prerogative rather than statute. But some matters (national security, foreign affairs, treaty-making, the armed forces, mercy) remain non-justiciable."},

{th:"The Crown & the Government",
 q:"'Wednesbury unreasonableness' describes a decision that is…",
 o:["merely debatable or unwise",
    "so unreasonable that no reasonable authority could ever have come to it",
    "disproportionate to its legitimate aim",
    "reached without a fair hearing"],
 a:1,
 e:"Associated Provincial Picture Houses v Wednesbury Corporation (1948) sets the high threshold for irrationality. Where Convention rights are engaged, the more intrusive proportionality test applies instead."},

{th:"The Crown & the Government",
 q:"Which ground of judicial review covers a breach of the rules of natural justice (e.g. the right to a fair hearing)?",
 o:["illegality","irrationality","procedural impropriety","proportionality"],
 a:2,
 e:"Procedural impropriety covers breaches of statutory procedure and of the common-law rules of natural justice — the right to a fair hearing and the rule against bias."},

{th:"The Crown & the Government",
 q:"The Cabinet is best described as…",
 o:["a body with statutory legal powers of its own",
    "the supreme directive authority of government, but a 'creature of convention'",
    "a committee of the House of Lords",
    "the head of the judiciary"],
 a:1,
 e:"The Cabinet is the supreme directive authority of central government, yet it has no formal legal powers of its own — it exists and operates by convention."}

];
